#!/usr/bin/env bash
# =============================================================================
# CDPI PoC — CREDEBL single-path initializer
# -----------------------------------------------------------------------------
# Single entry point for a complete CREDEBL deployment.
# Asks only 4-5 essential questions; all secrets are generated automatically.
#
# Usage:
#   bash scripts/init-credebl.sh
# =============================================================================

set -euo pipefail

# --- Paths -------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CREDEBL_DIR="$REPO_DIR/credebl"
ENV_TEMPLATE="$CREDEBL_DIR/.env.example"
ENV_FILE="$CREDEBL_DIR/.env"
MASTER_TABLE="$CREDEBL_DIR/config/credebl-master-table.json"
AGENT_RUNTIME_DIR="$CREDEBL_DIR/.agent-runtime"
AGENT_RUNTIME_ENV_FILE="$AGENT_RUNTIME_DIR/agent.env"

# --- Utility functions -------------------------------------------------------

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "Error: required command '$1' not found." >&2; exit 1; }
}

# Strip protocol and trailing slashes from a host input
sanitize_host() {
  local v
  v="$(printf '%s' "$1" | sed 's/^ *//;s/ *$//')"
  v="${v#http://}"
  v="${v#https://}"
  v="${v%%/*}"
  printf '%s' "$v"
}

ask() {
  local prompt="$1"
  local default="${2:-}"
  local secret="${3:-false}"
  local value

  while true; do
    if [ "$secret" = "true" ]; then
      [ -n "$default" ] \
        && printf "%s [press Enter for auto-generated value]: " "$prompt" >&2 \
        || printf "%s: " "$prompt" >&2
      read -r -s value
      printf "\n" >&2
    else
      [ -n "$default" ] \
        && printf "%s [%s]: " "$prompt" "$default" >&2 \
        || printf "%s: " "$prompt" >&2
      read -r value
    fi

    [ -z "$value" ] && value="$default"
    [ -n "$value" ] && { printf '%s' "$value"; return 0; }
    echo "A value is required." >&2
  done
}

ask_yes_no() {
  local prompt="$1"
  local default="${2:-N}"
  local reply suffix="[y/N]"
  [ "$default" = "Y" ] && suffix="[Y/n]"

  while true; do
    printf "%s %s: " "$prompt" "$suffix" >&2
    read -r reply
    reply="$(printf '%s' "$reply" | sed 's/^ *//;s/ *$//')"
    [ -z "$reply" ] && reply="$default"
    case "$reply" in
      [Yy]|[Yy][Ee][Ss]) return 0 ;;
      [Nn]|[Nn][Oo])     return 1 ;;
    esac
    echo "Please answer yes or no." >&2
  done
}

# Generate an HS256 JWT signed with JWT_TOKEN_SECRET for schema-file-server
generate_hs256_jwt() {
  python3 - "$1" "$2" <<'PY'
import base64, hashlib, hmac, json, sys, time

secret_input, issuer = sys.argv[1], sys.argv[2]
now = int(time.time())

try:
    secret = base64.b64decode(secret_input, validate=True)
    if not secret:
        secret = secret_input.encode("utf-8")
except Exception:
    secret = secret_input.encode("utf-8")

def b64url(data):
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")

h = b64url(json.dumps({"alg": "HS256", "typ": "JWT"}, separators=(",", ":")).encode())
p = b64url(json.dumps(
    {"iss": issuer, "sub": "schema-file-server", "iat": now, "exp": now + 315360000},
    separators=(",", ":"),
).encode())
sig = b64url(hmac.new(secret, f"{h}.{p}".encode("ascii"), hashlib.sha256).digest())
print(f"{h}.{p}.{sig}")
PY
}

write_agent_runtime_env() {
  mkdir -p "$AGENT_RUNTIME_DIR/agent-config" "$AGENT_RUNTIME_DIR/token" "$AGENT_RUNTIME_DIR/endpoints"

  # Guard against a previous run that left agent.env as a directory
  [ -d "$AGENT_RUNTIME_ENV_FILE" ] && rm -rf "$AGENT_RUNTIME_ENV_FILE"

  cat > "$AGENT_RUNTIME_ENV_FILE" <<EOF
# Generated by scripts/init-credebl.sh — do not edit manually
LEDGER_URL=http://test.bcovrin.vonx.io
GENESIS_URL=http://test.bcovrin.vonx.io/genesis
TAILS_FILE_SERVER=https://tails.vonx.io
AGENT_HTTP_URL=http://${VPS_HOST}
AGENT_WS_URL=ws://${VPS_HOST}
CONNECT_TIMEOUT=10
MAX_CONNECTIONS=1000
IDLE_TIMEOUT=30000
SESSION_ACQUIRE_TIMEOUT=2147483647
SESSION_LIMIT=2147483647
INMEMORY_LRU_CACHE_LIMIT=2147483647
TRUST_SERVICE_AUTH_TYPE=NoAuth
TRUST_LIST_URL=https://example.com/trust-list.json
EOF
}

wait_for_container_state() {
  local name="$1" pattern="$2" attempts="${3:-60}" i=1
  while [ "$i" -le "$attempts" ]; do
    docker inspect --format='{{.State.Status}} {{.State.ExitCode}}' "$name" 2>/dev/null \
      | grep -Eqi "$pattern" && return 0
    sleep 2
    i=$((i + 1))
  done
  return 1
}

# =============================================================================
# CONTAINER PATCHES
# =============================================================================
# CREDEBL container patches required for self-hosted MinIO and internal schemas.
# Applied after every `docker compose up` because patches live inside container
# filesystems and are lost when containers are recreated.
# Each patch is idempotent — safe to run on already-patched containers.

patch_utility_s3() {
  # AWS SDK v2 does NOT read AWS_ENDPOINT from environment automatically.
  # Without this patch, S3 calls from the utility service go to real AWS
  # and fail with "The AWS Access Key Id you provided does not exist".
  # We add endpoint + s3ForcePathStyle:true to all three S3 client constructors.
  # Uses docker cp + --user root because the process runs as uid=1001 (read-only /app).
  local patch_script
  patch_script="$(mktemp /tmp/patch_utility_XXXXXX.js)"
  cat > "$patch_script" << 'JSEOF'
const fs = require('fs');
const path = '/app/dist/apps/utility/main.js';
let content = fs.readFileSync(path, 'utf8');
if (content.includes('s3ForcePathStyle')) { process.stdout.write('already patched\n'); process.exit(0); }
content = content
  .replace(
    'region: process.env.AWS_REGION\n        });',
    'region: process.env.AWS_REGION,\n            endpoint: process.env.AWS_ENDPOINT,\n            s3ForcePathStyle: true\n        });'
  )
  .replace(
    'region: process.env.AWS_PUBLIC_REGION\n        });',
    'region: process.env.AWS_PUBLIC_REGION,\n            endpoint: process.env.AWS_ENDPOINT,\n            s3ForcePathStyle: true\n        });'
  )
  .replace(
    'region: process.env.AWS_S3_STOREOBJECT_REGION\n        });',
    'region: process.env.AWS_S3_STOREOBJECT_REGION,\n            endpoint: process.env.AWS_S3_STOREOBJECT_ENDPOINT || process.env.AWS_ENDPOINT,\n            s3ForcePathStyle: true\n        });'
  );
if (!content.includes('s3ForcePathStyle')) { process.stderr.write('ERROR: patch pattern not found — CREDEBL image may have changed\n'); process.exit(1); }
fs.writeFileSync(path, content);
process.stdout.write('patched\n');
JSEOF
  docker cp "$patch_script" credebl-utility:/tmp/patch_utility.js
  rm -f "$patch_script"
  docker exec --user root credebl-utility node /tmp/patch_utility.js
}

patch_api_gateway_context_validator() {
  # IsCredentialJsonLdContext validator calls isURL(v) with default require_tld:true.
  # This rejects Docker-internal hostnames like schema-file-server (no TLD).
  # Adding require_tld:false allows internal hostnames in @context arrays.
  #
  # Implementation notes:
  # - The api-gateway process runs as uid=1001 (nextjs), not root — cannot write to /app.
  # - Heredoc via `docker exec ... node -` is unreliable inside SSH quoted commands.
  # - Solution: write the patch script to a temp file on the host, docker cp it in,
  #   then exec as --user root.
  local patch_script
  patch_script="$(mktemp /tmp/patch_api_gw_XXXXXX.js)"
  cat > "$patch_script" << 'JSEOF'
const fs = require('fs');
const path = '/app/dist/apps/api-gateway/main.js';
let content = fs.readFileSync(path, 'utf8');
const target = '(0, class_validator_1.isURL)(v)';
const replacement = '(0, class_validator_1.isURL)(v, { require_tld: false })';
// Find the FUNCTION DEFINITION — the decorator usage appears ~33k chars earlier in the bundle
// so we must anchor to 'function IsCredentialJsonLdContext', not just 'IsCredentialJsonLdContext'.
const funcIdx = content.indexOf('function IsCredentialJsonLdContext');
if (funcIdx < 0) { process.stderr.write('ERROR: function IsCredentialJsonLdContext not found\n'); process.exit(1); }
const after = content.indexOf(target, funcIdx);
// The isURL call is ~500 chars after the function definition
if (after < 0 || after > funcIdx + 1000) { process.stdout.write('already patched\n'); process.exit(0); }
content = content.substring(0, after) + replacement + content.substring(after + target.length);
fs.writeFileSync(path, content);
process.stdout.write('patched\n');
JSEOF
  docker cp "$patch_script" credebl-api-gateway:/tmp/patch_api_gw.js
  rm -f "$patch_script"
  docker exec --user root credebl-api-gateway node /tmp/patch_api_gw.js
}

patch_credo_credential_events() {
  # The Credo root agent (multi-tenancy) does not expose agent.modules.credentials.
  # Without this patch, getFormatData() throws "Cannot read properties of undefined"
  # which crashes the event handler and causes ECONNREFUSED on retries.
  local credo_container
  credo_container="$(docker ps --format '{{.Names}}' | grep -v '^credebl-' | grep -v '^[0-9a-f]\{12\}_credebl' | head -1)"
  if [ -z "$credo_container" ]; then
    echo "  No Credo controller container found — skipping."
    return 0
  fi
  # Credo containers also run as uid=1001 — use docker cp + --user root.
  local patch_script
  patch_script="$(mktemp /tmp/patch_credo_XXXXXX.js)"
  cat > "$patch_script" << 'JSEOF'
const fs = require('fs');
const path = '/app/build/events/CredentialEvents.js';
let content = fs.readFileSync(path, 'utf8');
if (content.includes('getFormatData unavailable')) { process.stdout.write('already patched\n'); process.exit(0); }
const pattern = /^(\s+)const data = await agent\.modules\.credentials\.getFormatData\(record\.id\);\n\s+body\.credentialData = data;/m;
const m = content.match(pattern);
if (!m) { process.stderr.write('ERROR: patch target not found in CredentialEvents.js\n'); process.exit(1); }
const indent = m[1];
const replacement = `${indent}try {\n${indent}    if (agent.modules && agent.modules.credentials) {\n${indent}        const data = await agent.modules.credentials.getFormatData(record.id);\n${indent}        body.credentialData = data;\n${indent}    }\n${indent}} catch (e) {\n${indent}    // getFormatData unavailable in this agent context (e.g. multi-tenancy root agent)\n${indent}}`;
content = content.replace(pattern, replacement);
fs.writeFileSync(path, content);
process.stdout.write('patched\n');
JSEOF
  docker cp "$patch_script" "${credo_container}:/tmp/patch_credo.js"
  rm -f "$patch_script"
  local result
  result="$(docker exec --user root "$credo_container" node /tmp/patch_credo.js)"
  printf '%s\n' "$result"
  # Only restart Credo when the patch was actually applied — a restart regenerates
  # Credo's random secretKey, invalidating the stored tenant JWT. Skipping the
  # restart when already patched avoids a pointless JWT refresh cycle on re-runs.
  if [ "$result" = "patched" ]; then
    docker restart "$credo_container" >/dev/null
  fi
}

patch_credo_proof_events() {
  # Patch 7 — Credo ProofEvents.js crash in multi-tenancy root agent
  #
  # Two bugs in ProofEvents.js crash Credo when an OOB proof request is created:
  #
  # Bug A: contextCorrelationId starts with "tenant-" (it is a context correlation ID,
  # not a bare tenant UUID). getTenantAgent({tenantId: "tenant-abc..."}) throws:
  #   "Tenant id already starts with 'tenant-'. You are probably passing a context
  #    correlation id"
  # Fix A: strip the "tenant-" prefix before passing to getTenantAgent.
  #
  # Bug B: tenantAgent.proofs is undefined in the multi-tenancy root agent context.
  # Calling tenantAgent.proofs.getFormatData(record.id) throws TypeError, crashing
  # the event handler and causing ECONNRESET on the proof request.
  # Fix B: wrap the getFormatData call in try-catch (same pattern as Patch 3).
  #
  # _Symptom if missing_: POST /orgs/{id}/proofs/oob returns 500 "Something went wrong!"
  # with Credo log: CredoError "Tenant id already starts with 'tenant-'" → crash →
  # restart; after Fix A applied but before Fix B: TypeError "Cannot read properties of
  # undefined (reading 'getFormatData')" → crash → restart.
  local credo_container
  credo_container="$(docker ps --format '{{.Names}}' | grep -v '^credebl-' | grep -v '^[0-9a-f]\{12\}_credebl' | head -1)"
  if [ -z "$credo_container" ]; then
    echo "  No Credo controller container found — skipping."
    return 0
  fi
  local patch_script
  patch_script="$(mktemp /tmp/patch_proof_XXXXXX.js)"
  cat > "$patch_script" << 'JSEOF'
const fs = require('fs');
const path = '/app/build/events/ProofEvents.js';
let c = fs.readFileSync(path, 'utf8');
if (c.includes('proofData try-catch guard')) { process.stdout.write('already patched\n'); process.exit(0); }
// Fix A: strip "tenant-" prefix from contextCorrelationId before getTenantAgent
const tenantIdTarget = 'tenantId: event.metadata.contextCorrelationId,';
if (c.indexOf(tenantIdTarget) >= 0) {
  c = c.replace(tenantIdTarget,
    "tenantId: event.metadata.contextCorrelationId.indexOf('tenant-') === 0 ? event.metadata.contextCorrelationId.slice(7) : event.metadata.contextCorrelationId, // tenant- prefix guard");
}
// Fix B: wrap tenantAgent.proofs.getFormatData in try-catch
const getFormatTarget = 'const data = await tenantAgent.proofs.getFormatData(record.id);\n            body.proofData = data;';
if (c.indexOf(getFormatTarget) >= 0) {
  c = c.replace(getFormatTarget,
    'try { if (tenantAgent && tenantAgent.proofs) { const data = await tenantAgent.proofs.getFormatData(record.id); body.proofData = data; } } catch (e) { /* proofData try-catch guard */ }');
}
if (!c.includes('proofData try-catch guard')) { process.stderr.write('ERROR: patch target not found in ProofEvents.js\n'); process.exit(1); }
fs.writeFileSync(path, c);
process.stdout.write('patched\n');
JSEOF
  docker cp "$patch_script" "${credo_container}:/tmp/patch_proof.js"
  rm -f "$patch_script"
  local result
  result="$(docker exec --user root "$credo_container" node /tmp/patch_proof.js)"
  printf '%s\n' "$result"
  if [ "$result" = "patched" ]; then
    docker restart "$credo_container" >/dev/null
  fi
}

patch_issuance_schema_url() {
  # Studio's URL builder function incorrectly prepends http:// to URLs that already
  # have it (regex matches http://host:port/schemas/ as host:port/schemas/).
  # This patch strips duplicate http:// prefixes in getW3CSchemaAttributes before fetch.
  # Uses indexOf instead of regex literal to avoid escaping issues in heredoc.
  # Uses docker cp + --user root (issuance runs as uid=1001, read-only /app).
  local patch_script
  patch_script="$(mktemp /tmp/patch_issuance_XXXXXX.js)"
  cat > "$patch_script" << 'JSEOF'
const fs = require('fs');
const path = '/app/dist/apps/issuance/main.js';
let content = fs.readFileSync(path, 'utf8');
if (content.includes('indexOf("://http")')) { process.stdout.write('already patched\n'); process.exit(0); }
const target = 'async getW3CSchemaAttributes(schemaUrl) {';
if (!content.includes(target)) { process.stderr.write('ERROR: patch target not found\n'); process.exit(1); }
// Use slice+indexOf only — NO regex literals. A regex literal /^https?:\/\// inserted via
// string concatenation becomes /^https?:///, where // terminates the regex prematurely,
// causing "SyntaxError: missing ) after argument list" when the patched bundle is loaded.
const fixLines = ' while (schemaUrl && schemaUrl.indexOf("://http") > 0) { schemaUrl = schemaUrl.slice(schemaUrl.indexOf("://") + 3); }';
content = content.replace(target, target + fixLines);
fs.writeFileSync(path, content);
process.stdout.write('patched\n');
JSEOF
  docker cp "$patch_script" credebl-issuance:/tmp/patch_issuance.js
  rm -f "$patch_script"
  docker exec --user root credebl-issuance node /tmp/patch_issuance.js
}

patch_issuance_context_urls() {
  # Studio's credential offer builder triple-prepends http:// to @context URLs,
  # producing "http://http://http://schema-file-server:4000/schemas/...".
  # Credo rejects these malformed URLs with 400 "@context must be an array of strings".
  # This patch normalizes @context URL arrays in outOfBandCredentialOffer right
  # after the JSONLD branch validates/updates issuance dates.
  # Uses indexOf-based loop (no regex literals) and docker cp + --user root.
  local patch_script
  patch_script="$(mktemp /tmp/patch_issuance_ctx_XXXXXX.js)"
  cat > "$patch_script" << 'JSEOF'
const fs = require('fs');
const path = '/app/dist/apps/issuance/main.js';
let content = fs.readFileSync(path, 'utf8');
if (content.includes('ctx.map(function(url)')) { process.stdout.write('already patched\n'); process.exit(0); }
const target = "'Validated/Updated Issuance dates credential offer'";
const idx = content.indexOf(target);
if (idx < 0) { process.stderr.write('ERROR: patch target not found in issuance/main.js\n'); process.exit(1); }
// Insert normalization right after the logger.debug call's closing semicolon
const insertAfter = content.indexOf(';', idx) + 1;
const normCode = ' if (credentialOffer) { for (const offer of credentialOffer) { const ctx = offer && offer.credential && offer.credential["@context"]; if (Array.isArray(ctx)) { offer.credential["@context"] = ctx.map(function(url) { while (typeof url === "string" && url.indexOf("://http") > 0) { url = url.slice(url.indexOf("://") + 3); } return url; }); } } }';
content = content.substring(0, insertAfter) + normCode + content.substring(insertAfter);
fs.writeFileSync(path, content);
process.stdout.write('patched\n');
JSEOF
  docker cp "$patch_script" credebl-issuance:/tmp/patch_issuance_ctx.js
  rm -f "$patch_script"
  docker exec --user root credebl-issuance node /tmp/patch_issuance_ctx.js
}

patch_agent_service_create_tenant() {
  # agent-service._createTenantWallet sends the Platform-admin's tenant JWT
  # (RestTenantAgent) as the Authorization header when calling Credo's
  # /multi-tenancy/create-tenant. Credo requires a root JWT (RestRootAgentWithTenants)
  # for this operation — the tenant JWT is silently rejected (empty response body),
  # so walletResponseDetails.id is undefined and org_agents stays at
  # agentSpinUpStatus=1 with empty tenantId/apiKey. Every new org's shared wallet
  # creation fails with this bug.
  # Fix: exchange for root JWT via /agent/token before calling create-tenant.
  local patch_script
  patch_script="$(mktemp /tmp/patch_agent_ct_XXXXXX.js)"
  cat > "$patch_script" << 'JSEOF'
const fs = require('fs');
const path = '/app/dist/apps/agent-service/main.js';
let content = fs.readFileSync(path, 'utf8');
if (content.includes('PATCH: create-tenant needs root JWT')) { process.stdout.write('already patched\n'); process.exit(0); }
const target = 'const tenantDetails = await this.commonService.httpPost(`${endpoint}${common_constant_1.CommonConstants.URL_SHAGENT_CREATE_TENANT}`, createTenantOptions, { headers: { authorization: agentApiKey } });\n        return tenantDetails;\n    }\n    async handleCreateDid';
if (!content.includes(target)) { process.stderr.write('ERROR: patch target not found in agent-service/main.js\n'); process.exit(1); }
const replacement = 'const rootTokenResp = await this.commonService.httpPost(endpoint + "/agent/token", {}, { headers: { authorization: process.env.AGENT_API_KEY } }); // PATCH: create-tenant needs root JWT\n        const rootJwt = "Bearer " + ((rootTokenResp && rootTokenResp.token) || (rootTokenResp && rootTokenResp.access_token) || "");\n        const tenantDetails = await this.commonService.httpPost(`${endpoint}${common_constant_1.CommonConstants.URL_SHAGENT_CREATE_TENANT}`, createTenantOptions, { headers: { authorization: rootJwt } });\n        return tenantDetails;\n    }\n    async handleCreateDid';
content = content.replace(target, replacement);
fs.writeFileSync(path, content);
process.stdout.write('patched\n');
JSEOF
  docker cp "$patch_script" credebl-agent-service:/tmp/patch_agent_ct.js
  rm -f "$patch_script"
  docker exec --user root credebl-agent-service node /tmp/patch_agent_ct.js
}

ensure_sendgrid_from_address() {
  # The FROM address used at email-send time is read from platform_config.emailFrom
  # in Postgres — NOT from the EMAIL_FROM env var. The seed populates this column
  # with whatever default it has compiled in (noreply@cdpi-poc.local), regardless
  # of what EMAIL_FROM is set to in .env.
  #
  # For SendGrid to accept the outbound email, emailFrom MUST be a verified sender
  # address in the SendGrid account. This function updates the DB row directly.
  echo
  echo "Updating platform_config.emailFrom for SendGrid..."
  local current
  current="$(docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -Atqc 'SELECT "emailFrom" FROM platform_config LIMIT 1;' \
    2>/dev/null | tr -d '\r')"
  if [ "$current" = "$EMAIL_FROM_VAL" ]; then
    echo "  emailFrom already set to: ${EMAIL_FROM_VAL} — skipping."
    return 0
  fi
  docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -v ON_ERROR_STOP=1 -c \
    "UPDATE platform_config SET \"emailFrom\" = '${EMAIL_FROM_VAL}';" >/dev/null
  echo "  platform_config.emailFrom updated: ${current} → ${EMAIL_FROM_VAL}"
  # Restart user + issuance so any in-memory cached config is invalidated
  docker compose restart user issuance >/dev/null
  sleep 10
  echo "  User and issuance services restarted."
}

ensure_brand_logo() {
  # Upload CREDEBL logo to MinIO orgLogos/ and set BRAND_LOGO in .env.
  # The issuance email template uses BRAND_LOGO for the header image.
  # Without it the email shows a broken <img src="undefined"> tag.
  if grep -q '^BRAND_LOGO=' "$ENV_FILE" 2>/dev/null; then
    echo "  BRAND_LOGO already configured — skipping logo upload."
    return 0
  fi
  echo "  Uploading CREDEBL logo to MinIO..."
  # Copy logo from Studio image (always present) to MinIO orgLogos/
  docker cp credebl-studio:/app/public/images/CREDEBL_LOGO.png /tmp/credebl-logo-upload.png 2>/dev/null
  if [ ! -f /tmp/credebl-logo-upload.png ]; then
    echo "  WARNING: Could not find logo in Studio container — skipping."
    return 0
  fi
  docker cp /tmp/credebl-logo-upload.png credebl-minio:/tmp/credebl-logo-upload.png 2>/dev/null
  docker exec credebl-minio mc alias set cdpi http://localhost:9000 \
    "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" --quiet 2>/dev/null
  docker exec credebl-minio mc cp /tmp/credebl-logo-upload.png \
    cdpi/credebl-bucket/orgLogos/credebl-logo.png 2>/dev/null
  rm -f /tmp/credebl-logo-upload.png
  LOGO_URL="http://${VPS_IP}:9000/credebl-bucket/orgLogos/credebl-logo.png"
  printf '\n# Email branding — set by init-credebl.sh\nBRAND_LOGO=%s\nIOS_DOWNLOAD_LINK=https://apps.apple.com/in/app/inji-wallet/id1631979601\n' "$LOGO_URL" >> "$ENV_FILE"
  echo "  Logo available at: $LOGO_URL"
  echo "  BRAND_LOGO and IOS_DOWNLOAD_LINK added to .env — restarting issuance..."
  # Use docker restart (not compose up --force-recreate) to avoid cascading other containers
  # and losing in-container patches that were applied earlier.
  docker restart credebl-issuance >/dev/null 2>&1 &
  sleep 5
}

apply_container_patches() {
  echo
  echo "Applying CREDEBL container patches..."
  echo -n "  Utility service S3 → MinIO endpoint: "
  patch_utility_s3
  docker compose restart utility >/dev/null

  echo -n "  API gateway @context validator (require_tld): "
  patch_api_gateway_context_validator
  docker compose restart api-gateway >/dev/null

  echo -n "  Issuance service schema URL deduplication: "
  patch_issuance_schema_url
  echo -n "  Issuance service @context URL normalization: "
  patch_issuance_context_urls
  docker compose restart issuance >/dev/null

  echo -n "  Agent-service shared wallet create-tenant (root JWT): "
  patch_agent_service_create_tenant
  docker compose restart agent-service >/dev/null

  echo "  Waiting for restarted containers to be ready..."
  local deadline=$(( $(date +%s) + 90 ))
  while [ "$(date +%s)" -lt "$deadline" ]; do
    local gw_health as_log
    gw_health="$(docker inspect credebl-api-gateway --format '{{.State.Health.Status}}' 2>/dev/null || true)"
    as_log="$(docker logs credebl-agent-service --tail=5 2>/dev/null || true)"
    [ "$gw_health" = "healthy" ] \
      && printf '%s' "$as_log" | grep -q 'listening to NATS' \
      && break
    sleep 3
  done
  echo "  Patches applied."
}

ensure_minio_setup() {
  echo
  echo "Ensuring MinIO buckets and access keys are initialized..."
  docker compose up -d minio >/dev/null

  local attempt=1
  while [ "$attempt" -le 5 ]; do
    docker compose rm -sf minio-setup >/dev/null 2>&1 || true
    if docker compose up --no-deps minio-setup \
       && wait_for_container_state "credebl-minio-setup" '^exited 0$' 10; then
      echo "MinIO setup complete."
      return 0
    fi
    echo "  MinIO setup failed (attempt $attempt/5). Retrying..."
    attempt=$((attempt + 1))
    sleep 3
  done

  echo "Error: minio-setup did not complete successfully." >&2
  echo "Inspect with: docker compose logs --tail=200 minio-setup" >&2
  return 1
}

platform_admin_shared_agent_ready() {
  local row status endpoint token_url
  row="$(docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -Atqc "
      SELECT COALESCE(oa.\"agentSpinUpStatus\"::text, ''),
             COALESCE(oa.\"agentEndPoint\", '')
      FROM organisation o
      LEFT JOIN org_agents oa ON oa.\"orgId\" = o.id
      WHERE o.name = 'Platform-admin'
      LIMIT 1;" 2>/dev/null | tr -d '\r')"

  status="${row%%|*}"
  endpoint="${row#*|}"

  [ "$status" != "2" ] && return 1
  [ -z "$endpoint" ] || [ "$endpoint" = "http://" ] || [ "$endpoint" = "https://" ] && return 1

  [[ "$endpoint" =~ ^https?:// ]] \
    && token_url="${endpoint%/}/agent/token" \
    || token_url="http://${endpoint}/agent/token"

  curl -sf --max-time 8 -X POST -H "Authorization: $AGENT_API_KEY" "$token_url" >/dev/null
}

# Kill all Credo controller containers that were spawned outside of docker compose.
# Uses two complementary strategies because the image-ancestor filter alone is unreliable:
#   1. Ancestor filter — works when the image tag hasn't changed.
#   2. Name pattern  — agent-provisioning always names these containers as
#      "{org-uuid}_{ContainerName}" (e.g. "c1f8a28f-71a3-..._Platform-admin").
#      Matching on the UUID prefix catches them regardless of image tag or pull history.
purge_stale_credo_containers() {
  local found=0 names

  # Strategy 1: by image ancestor
  names=$(docker ps -a \
    --filter "ancestor=ghcr.io/credebl/credo-controller:latest" \
    --format "{{.Names}}" 2>/dev/null || true)
  if [ -n "$names" ]; then
    echo "$names" | xargs docker rm -f 2>/dev/null || true
    echo "  Removed by image: $(printf '%s' "$names" | tr '\n' ' ')"
    found=1
  fi

  # Strategy 2: by name pattern — agent-provisioning names containers as
  # "{org-uuid}_{ContainerName}" (e.g. "c1f8a28f-..._Platform-admin").
  # Avoid grep-in-pipeline inside $() — with set -euo pipefail, grep's exit 1
  # (no match) can escape the || true guard and kill the script. Use a while-read
  # loop with bash regex instead, which has no pipeline exit-code hazard.
  names=""
  while IFS= read -r cname; do
    [[ "$cname" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}_ ]] \
      && names="${names}${cname}"$'\n' || true
  done < <(docker ps -a --format "{{.Names}}" 2>/dev/null || true)
  if [ -n "$names" ]; then
    printf '%s' "$names" | xargs docker rm -f 2>/dev/null || true
    echo "  Removed by name pattern: $(printf '%s' "$names" | tr '\n' ' ')"
    found=1
  fi

  [ "$found" -eq 0 ] && echo "  No stale Credo containers found." || true
}

clear_stale_platform_admin_agent() {
  # Remove the incomplete org_agents record so agent-service will try again.
  docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -v ON_ERROR_STOP=1 -c "
      DELETE FROM org_agents oa
      USING organisation o
      WHERE oa.\"orgId\" = o.id
        AND o.name = 'Platform-admin'
        AND (
          oa.\"agentSpinUpStatus\" <> 2
          OR COALESCE(oa.\"agentEndPoint\", '') = ''
        );" >/dev/null

  # Credo (askar) creates a separate PostgreSQL database named after the wallet.
  # If a previous provision attempt failed mid-way, that database still exists and
  # the next attempt throws "Your wallet is already been created". Drop it so the
  # next agent-service startup can provision the wallet cleanly from scratch.
  docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d postgres -c "
      SELECT pg_terminate_backend(pid)
      FROM pg_stat_activity
      WHERE datname = '${PLATFORM_WALLET_NAME}';
      DROP DATABASE IF EXISTS \"${PLATFORM_WALLET_NAME}\";" >/dev/null 2>&1 || true
}

# Handles the "container running but endpoint never written" race condition.
# CREDEBL's agent-service can restart mid-provisioning, lose the NATS response from
# agent-provisioning, and leave agentSpinUpStatus=1 with an empty agentEndPoint even
# though the Credo container is healthy. This function detects that state, extracts the
# admin port from the running container, tests it, and patches the DB directly.
recover_orphan_running_agent() {
  local container port endpoint

  # Look for a running (not exited) Credo container whose name matches the UUID pattern
  container=$(docker ps --format "{{.Names}}" 2>/dev/null \
    | grep -E "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}_Platform-admin$" \
    | head -1 || true)
  [ -z "$container" ] && return 1

  echo "  Found running agent container: $container"

  # Extract the host-side admin port (8xxx range — that's the Credo REST API port)
  # `docker port` output: "8006/tcp -> 0.0.0.0:8006" — $NF is always the host port
  port=$(docker port "$container" 2>/dev/null \
    | awk -F'[/: ]' '$1+0 >= 8000 && $1+0 < 9000 { print $NF; exit }')
  [ -z "$port" ] && { echo "  Could not determine admin port for $container"; return 1; }

  endpoint="http://${VPS_HOST}:${port}"
  echo "  Testing agent endpoint: ${endpoint}/agent/token"

  if ! curl -sf --max-time 10 -X POST \
      -H "Authorization: $AGENT_API_KEY" "${endpoint}/agent/token" >/dev/null; then
    echo "  Agent container is running but not responding on ${endpoint}"
    return 1
  fi

  echo "  Agent is responding. Patching DB record (status=2, endpoint=${endpoint})..."
  docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -v ON_ERROR_STOP=1 -c "
      UPDATE org_agents oa
      SET \"agentSpinUpStatus\" = 2,
          \"agentEndPoint\"     = '${endpoint}'
      FROM organisation o
      WHERE oa.\"orgId\" = o.id
        AND o.name = 'Platform-admin';" >/dev/null

  echo "  Restarting agent-service so it picks up the updated endpoint..."
  docker compose restart agent-service >/dev/null
  sleep 20
}

ensure_platform_admin_shared_agent() {
  echo
  echo "Ensuring platform-admin shared agent is initialized..."

  if ! wait_for_container_state "credebl-platform-admin-bootstrap" '^exited 0$' 90; then
    echo "Error: platform-admin-bootstrap did not complete." >&2
    echo "Inspect with: docker compose logs --tail=200 platform-admin-bootstrap" >&2
    return 1
  fi

  local attempt=1
  while [ "$attempt" -le 12 ]; do
    if platform_admin_shared_agent_ready; then
      echo "Platform-admin shared agent is ready."
      return 0
    fi

    echo "  Not ready yet (attempt $attempt/12). Clearing stale state and restarting..."
    clear_stale_platform_admin_agent || true
    purge_stale_credo_containers
    docker compose up -d cloud-wallet >/dev/null
    docker compose restart agent-provisioning agent-service >/dev/null
    # The full provision cycle takes ~40s: Nest startup + Prisma migrate + wallet init + agent start.
    # Waiting only 10s means we restart again before the previous attempt finishes, making it worse.
    echo "  Waiting 50s for provisioning cycle to complete..."
    sleep 50
    attempt=$((attempt + 1))
  done

  # All retries exhausted. The Credo container may be running but the endpoint was never
  # written to the DB (race condition: agent-service restarted mid-NATS response). Try
  # to recover by detecting and patching the orphan container before giving up.
  echo "  Retries exhausted. Attempting orphan-container recovery..."
  if recover_orphan_running_agent && platform_admin_shared_agent_ready; then
    echo "Platform-admin shared agent is ready (recovered from orphan container)."
    return 0
  fi

  echo "Error: platform-admin shared agent did not reach ready state." >&2
  echo "Inspect with: docker compose logs --tail=200 agent-service agent-provisioning" >&2
  return 1
}

# Create a multi-tenancy tenant for the Platform-admin org inside the shared Credo
# agent and store the encrypted tenant JWT in org_agents.apiKey. This is required
# because CREDEBL's agent-service (DEDICATED type) passes the decrypted apiKey
# directly as the Authorization header on Credo calls — Credo routes by the
# tenantId embedded in the RestTenantAgent JWT.
#
# The tenant JWT is signed with Credo's random secretKey (generated at container
# startup and stored in Askar wallet). It does NOT expire (no exp claim) and
# remains valid as long as the Credo container is not restarted. If the Credo
# container is ever restarted, re-run this function to refresh the stored JWT.
ensure_platform_admin_tenant() {
  echo
  echo "Ensuring Platform-admin tenant wallet is set up in the Credo agent..."

  # Get the agent endpoint from DB
  local endpoint tenant_id
  endpoint="$(docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -Atqc "
      SELECT oa.\"agentEndPoint\" FROM org_agents oa
      JOIN organisation o ON o.id = oa.\"orgId\"
      WHERE o.name = 'Platform-admin' AND oa.\"agentSpinUpStatus\" = 2
      LIMIT 1;" 2>/dev/null | tr -d '\r')"

  if [ -z "$endpoint" ]; then
    echo "  Error: Platform-admin agent endpoint not found in DB." >&2
    return 1
  fi

  # Normalize endpoint (ensure http:// prefix)
  [[ "$endpoint" =~ ^https?:// ]] || endpoint="http://${endpoint}"

  # Get Credo root JWT — retry up to 8 times (40s total) to handle Credo still
  # starting up after being restarted by patch_credo_credential_events.
  # Credo's /agent/token returns {"token":"..."} — NOT {"access_token":"..."}.
  local root_jwt attempt=1
  while [ "$attempt" -le 8 ]; do
    root_jwt="$(curl -sf --max-time 10 -X POST \
      -H "Authorization: $AGENT_API_KEY" \
      "${endpoint}/agent/token" 2>/dev/null \
      | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('token', d.get('access_token','')))" 2>/dev/null || true)"
    [ -n "$root_jwt" ] && break
    echo "  Credo not ready yet (attempt ${attempt}/8), waiting 5s..."
    sleep 5
    attempt=$((attempt + 1))
  done

  if [ -z "$root_jwt" ]; then
    echo "  Error: Failed to get root JWT from Credo agent at ${endpoint} after retries." >&2
    return 1
  fi

  # Check if tenant already exists in DB
  tenant_id="$(docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -Atqc "
      SELECT COALESCE(oa.\"tenantId\", '') FROM org_agents oa
      JOIN organisation o ON o.id = oa.\"orgId\"
      WHERE o.name = 'Platform-admin'
      LIMIT 1;" 2>/dev/null | tr -d '\r')"

  if [ -z "$tenant_id" ]; then
    # Create tenant in Credo.
    # Payload: only "config" — the "jwt" field is excess and rejected by Credo's validator.
    # Response: {"id":"<tenantId>","token":"<RestTenantAgent JWT>",...}
    echo "  Creating Platform-admin tenant in Credo multi-tenant agent..."
    local create_resp
    create_resp="$(curl -sf --max-time 15 -X POST \
      -H "Authorization: Bearer ${root_jwt}" \
      -H "Content-Type: application/json" \
      -d '{"config":{"label":"Platform-admin"}}' \
      "${endpoint}/multi-tenancy/create-tenant" 2>/dev/null || true)"

    tenant_id="$(printf '%s' "$create_resp" | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('id',''))" 2>/dev/null || true)"
    if [ -z "$tenant_id" ]; then
      echo "  Error: Failed to create tenant. Response: $create_resp" >&2
      return 1
    fi
    echo "  Tenant created: $tenant_id"
  else
    echo "  Tenant already exists: $tenant_id"
  fi

  # Get a fresh tenant JWT via get-token (valid for the current Credo secretKey).
  # Response: {"token":"<RestTenantAgent JWT>"} — NOT {"access_token":"..."}.
  local tenant_jwt
  tenant_jwt="$(curl -sf --max-time 10 -X POST \
    -H "Authorization: Bearer ${root_jwt}" \
    "${endpoint}/multi-tenancy/get-token/${tenant_id}" 2>/dev/null \
    | python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('token', d.get('access_token','')))" 2>/dev/null || true)"

  if [ -z "$tenant_jwt" ]; then
    echo "  Error: Failed to get tenant JWT for tenant ${tenant_id}." >&2
    return 1
  fi

  # Encrypt tenant JWT with CryptoJS AES (same as CREDEBL's dataEncryption method)
  local encrypted_jwt
  encrypted_jwt="$(docker compose exec -T agent-service node -e "
const CryptoJS = require('crypto-js');
const token = '${tenant_jwt}';
const key = process.env.CRYPTO_PRIVATE_KEY;
const encrypted = CryptoJS.AES.encrypt(JSON.stringify(token), key).toString();
process.stdout.write(encrypted);
" 2>/dev/null)"

  if [ -z "$encrypted_jwt" ]; then
    echo "  Error: Failed to encrypt tenant JWT." >&2
    return 1
  fi

  # Update DB: set tenantId and apiKey
  docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -v ON_ERROR_STOP=1 -c "
      UPDATE org_agents oa
      SET \"tenantId\" = '${tenant_id}',
          \"apiKey\"   = '${encrypted_jwt}'
      FROM organisation o
      WHERE oa.\"orgId\" = o.id
        AND o.name = 'Platform-admin';" >/dev/null

  echo "  Platform-admin tenant wallet configured (tenantId=${tenant_id})."

  # Restart agent-service so it picks up the new apiKey on next request
  # Restart agent-service so it picks up the refreshed apiKey on the next request.
  # Give it 20s for Nest bootstrap + Prisma migration + NATS reconnect.
  docker compose restart agent-service >/dev/null
  sleep 20
  echo "  Agent-service restarted."
}

# =============================================================================
# PREREQUISITE CHECKS
# =============================================================================

require_cmd docker
require_cmd python3
require_cmd openssl
require_cmd curl

if ! docker info >/dev/null 2>&1; then
  echo "Error: Docker is not running or this user cannot access it." >&2
  exit 1
fi

[ -f "$ENV_TEMPLATE" ] || { echo "Error: template not found at $ENV_TEMPLATE" >&2; exit 1; }
[ -f "$MASTER_TABLE" ]  || { echo "Error: seed config not found at $MASTER_TABLE" >&2; exit 1; }

# =============================================================================
# INTERACTIVE PROMPTS — 4 questions, 5 if SSL is requested
# =============================================================================

cat <<'BANNER'
============================================================
 CDPI PoC — CREDEBL initializer
============================================================
 Answers 4 questions. All secrets are auto-generated and
 printed in full at the end — save that report securely.
============================================================
BANNER
echo

# 1. VPS host — autodetect with fallback
DETECTED_IP="$(curl -4 -fsS --max-time 5 ifconfig.me 2>/dev/null \
  || hostname -I 2>/dev/null | awk '{print $1}' \
  || true)"
DETECTED_IP="$(sanitize_host "${DETECTED_IP:-}")"

VPS_HOST="$(ask "VPS public IP or hostname (without http://)" "$DETECTED_IP")"
VPS_HOST="$(sanitize_host "$VPS_HOST")"

# 2. Keycloak host — default to same VPS but can be different
KEYCLOAK_HOST="$(ask "Keycloak host (press Enter if same as VPS)" "$VPS_HOST")"
KEYCLOAK_HOST="$(sanitize_host "$KEYCLOAK_HOST")"

# 3. Platform admin email
PLATFORM_ADMIN_EMAIL="$(ask "Platform admin email" "admin@cdpi-poc.local")"

# 4. SSL / Let's Encrypt
ENABLE_SSL=false
SSL_KEYCLOAK_DOMAIN=""
SSL_VPS_DOMAIN=""
if ask_yes_no "Enable HTTPS with Let's Encrypt certificates?" "N"; then
  ENABLE_SSL=true

  # 5a. Keycloak domain — suggest KEYCLOAK_HOST only if it looks like an FQDN, not a raw IP
  _kc_default="$KEYCLOAK_HOST"
  printf '%s' "$KEYCLOAK_HOST" | grep -Eq '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' && _kc_default=""
  SSL_KEYCLOAK_DOMAIN="$(ask "Keycloak domain for the SSL certificate (DNS must point to this VPS)" "$_kc_default")"
  SSL_KEYCLOAK_DOMAIN="$(sanitize_host "$SSL_KEYCLOAK_DOMAIN")"

  # 5b. General VPS domain (optional) — for API Gateway / Studio; skipped when same as Keycloak domain
  _vps_default="$VPS_HOST"
  printf '%s' "$VPS_HOST" | grep -Eq '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' && _vps_default=""
  if [ -z "$_vps_default" ] || [ "$_vps_default" != "$SSL_KEYCLOAK_DOMAIN" ]; then
    if ask_yes_no "Also issue an SSL certificate for the general VPS domain (API / Studio)?" "N"; then
      SSL_VPS_DOMAIN="$(ask "General VPS domain for the SSL certificate (DNS must point to this VPS)" "$_vps_default")"
      SSL_VPS_DOMAIN="$(sanitize_host "$SSL_VPS_DOMAIN")"
    fi
  fi
fi

# 5. Email provider
USE_SENDGRID=false
SENDGRID_API_KEY_VAL="SG.mock-not-used"
EMAIL_FROM_VAL="noreply@cdpi-poc.local"
if ask_yes_no "Send real emails via SendGrid? (No = capture all emails locally with Mailpit)" "N"; then
  USE_SENDGRID=true
  while true; do
    SENDGRID_API_KEY_VAL="$(ask "SendGrid API key (must start with SG.)")"
    [[ "$SENDGRID_API_KEY_VAL" == SG.* ]] && break
    echo "  Error: key must start with 'SG.' — try again." >&2
  done
  EMAIL_FROM_VAL="$(ask "From address (must be a verified SendGrid sender)" "noreply@cdpi-poc.local")"
fi

# =============================================================================
# GENERATE ALL SECRETS
# =============================================================================

POSTGRES_PASSWORD="$(openssl rand -hex 16)"
KEYCLOAK_ADMIN_PASSWORD="$(openssl rand -hex 16)"
KEYCLOAK_CLIENT_SECRET="$(openssl rand -hex 32)"
PLATFORM_ADMIN_INITIAL_PASSWORD="$(openssl rand -hex 8)"   # 16 hex chars — easy to type
MINIO_ROOT_PASSWORD="$(openssl rand -hex 16)"
AWS_ACCESS_KEY_ID="credebls3"
AWS_SECRET_ACCESS_KEY="$(openssl rand -hex 16)"
PLATFORM_SEED="$(openssl rand -hex 16)"
PLATFORM_WALLET_NAME="platformadminwallet"
PLATFORM_WALLET_PASSWORD="$(openssl rand -hex 16)"
AGENT_API_KEY="$(openssl rand -hex 32)"
JWT_SECRET="$(openssl rand -hex 32)"
NEXTAUTH_SECRET="$(openssl rand -hex 32)"
# base64 required — schema-file-server decodes it before signing JWTs
JWT_TOKEN_SECRET="$(openssl rand -base64 32 | tr -d '\n')"
# CRYPTO_PRIVATE_KEY must match platformAdminData.password encryption in master-table.json
# Keep the PoC default so the seeded admin password decrypts correctly on first boot
CRYPTO_PRIVATE_KEY="cdpi-poc-crypto-key-change-me"
# Keycloak admin client credentials used by the seed to call the Keycloak Admin REST API.
# ADMIN_KEYCLOAK_ID   = client_id  of the admin client (same as PLATFORM_ADMIN_KEYCLOAK_ID)
# ADMIN_KEYCLOAK_SECRET = client_secret of that client (same as KEYCLOAK_CLIENT_SECRET)
# Required by CREDEBL seed >= v1.x. Our bootstrap handles the 409 (user already exists)
# gracefully, so seed + bootstrap can both run without conflict.
ADMIN_KEYCLOAK_ID="adminClient"
ADMIN_KEYCLOAK_SECRET="$KEYCLOAK_CLIENT_SECRET"

# JWT signed with JWT_TOKEN_SECRET — required for W3C / did:web / did:key schema creation
SCHEMA_FILE_SERVER_TOKEN="$(generate_hs256_jwt "$JWT_TOKEN_SECRET" "Credebl")"

# =============================================================================
# DERIVE ALL URLS
# =============================================================================

PROTOCOL="http"

# Internal URLs — CREDEBL microservices reach Keycloak inside Docker.
# Always use the Docker service name for internal traffic; Keycloak runs in the
# same Docker Compose stack regardless of what public subdomain it is assigned.
# Using the external hostname here causes the admin API to return 403 when
# KC_HOSTNAME is set to an HTTPS domain (issuer mismatch on the admin API path).
KEYCLOAK_DOMAIN_INTERNAL="http://keycloak:8080/"
KEYCLOAK_ADMIN_URL_INTERNAL="http://keycloak:8080"

# Public URL — used by wallets and browsers; becomes HTTPS when SSL is enabled
if [ "$ENABLE_SSL" = "true" ]; then
  KEYCLOAK_PUBLIC_URL="https://${SSL_KEYCLOAK_DOMAIN}"
else
  KEYCLOAK_PUBLIC_URL="http://${KEYCLOAK_HOST}:8080"
fi

# When a VPS domain with SSL is configured, Studio and the API gateway are both
# served from that domain via nginx on port 443 — no bare port in the URL.
# NEXT_PUBLIC_BASE_URL is baked into the Studio bundle at build time, so
# PROTOCOL must be set to https here (before docker compose build runs) rather
# than being patched afterwards by setup-keycloak-https.sh.
if [ "$ENABLE_SSL" = "true" ] && [ -n "$SSL_VPS_DOMAIN" ]; then
  PROTOCOL="https"
  VPS_PUBLIC_HOST="$SSL_VPS_DOMAIN"
else
  VPS_PUBLIC_HOST="$VPS_HOST"
fi

if [ "$PROTOCOL" = "https" ]; then
  STUDIO_URL="https://${VPS_PUBLIC_HOST}"
  API_ENDPOINT="${VPS_PUBLIC_HOST}"         # bare host, no port — nginx proxies on 443
  PLATFORM_WEB_URL="https://${VPS_PUBLIC_HOST}"
  SOCKET_HOST="https://${VPS_PUBLIC_HOST}"
else
  STUDIO_URL="http://${VPS_PUBLIC_HOST}:3000"
  API_ENDPOINT="${VPS_PUBLIC_HOST}:5000"    # bare host:port — no protocol prefix
  PLATFORM_WEB_URL="http://${VPS_PUBLIC_HOST}:5000"
  SOCKET_HOST="http://${VPS_PUBLIC_HOST}:5000"
fi
ENABLE_CORS_IP_LIST="${STUDIO_URL},http://localhost:3000,http://127.0.0.1:3000"
# DEEPLINK_DOMAIN: prepended to /default/{uuid} to build the Accept Credential link.
# Points to MinIO so wallets can fetch the OOB invitation JSON stored there.
# SHORTENED_URL_DOMAIN is set to empty — the utility service builds /default/{uuid}
# which gets concatenated directly onto DEEPLINK_DOMAIN.
DEEPLINK_DOMAIN="http://${VPS_HOST}:9000/credebl-bucket"

# =============================================================================
# WRITE .env FROM TEMPLATE
# =============================================================================

if [ -f "$ENV_FILE" ]; then
  if ! ask_yes_no "Existing $ENV_FILE found. Overwrite it?" "N"; then
    echo "Aborted. Existing .env left untouched."
    exit 0
  fi
fi

export ENV_TEMPLATE ENV_FILE MASTER_TABLE \
  POSTGRES_PASSWORD KEYCLOAK_ADMIN_PASSWORD KEYCLOAK_CLIENT_SECRET \
  PLATFORM_ADMIN_INITIAL_PASSWORD MINIO_ROOT_PASSWORD \
  AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY \
  PLATFORM_SEED PLATFORM_WALLET_NAME PLATFORM_WALLET_PASSWORD \
  AGENT_API_KEY JWT_SECRET NEXTAUTH_SECRET JWT_TOKEN_SECRET \
  SCHEMA_FILE_SERVER_TOKEN CRYPTO_PRIVATE_KEY ADMIN_KEYCLOAK_ID ADMIN_KEYCLOAK_SECRET \
  PLATFORM_ADMIN_EMAIL VPS_HOST VPS_PUBLIC_HOST KEYCLOAK_HOST PROTOCOL \
  KEYCLOAK_DOMAIN_INTERNAL KEYCLOAK_ADMIN_URL_INTERNAL KEYCLOAK_PUBLIC_URL \
  STUDIO_URL API_ENDPOINT PLATFORM_WEB_URL SOCKET_HOST ENABLE_CORS_IP_LIST DEEPLINK_DOMAIN \
  USE_SENDGRID SENDGRID_API_KEY_VAL EMAIL_FROM_VAL

python3 <<'PY'
import json, os, re
from pathlib import Path

env_template = Path(os.environ["ENV_TEMPLATE"])
env_file     = Path(os.environ["ENV_FILE"])
master_table = Path(os.environ["MASTER_TABLE"])
e = os.environ.__getitem__

text = env_template.read_text(encoding="utf-8")

# Each entry replaces the matching KEY=... line in the template.
# Derived compound values (DATABASE_URL, etc.) are computed here.
replacements = {
    "POSTGRES_PASSWORD":                e("POSTGRES_PASSWORD"),
    "DATABASE_URL":                     f"postgresql://credebl:{e('POSTGRES_PASSWORD')}@postgres:5432/credebl",
    "POOL_DATABASE_URL":                f"postgresql://credebl:{e('POSTGRES_PASSWORD')}@postgres:5432/credebl",
    "KEYCLOAK_ADMIN_PASSWORD":          e("KEYCLOAK_ADMIN_PASSWORD"),
    "KEYCLOAK_DOMAIN":                  e("KEYCLOAK_DOMAIN_INTERNAL"),
    "KEYCLOAK_ADMIN_URL":               e("KEYCLOAK_ADMIN_URL_INTERNAL"),
    "KEYCLOAK_CLIENT_SECRET":           e("KEYCLOAK_CLIENT_SECRET"),
    "KEYCLOAK_MANAGEMENT_CLIENT_SECRET": e("KEYCLOAK_CLIENT_SECRET"),
    # MUST be credebl-client (NOT adminClient). adminClient tokens lack
    # resource_access.credebl-client.roles, which causes all org-level endpoints
    # (GET /orgs/{id}, POST /orgs/{id}/agents/wallet, etc.) to return 403
    # "User does not have access" even when the user has the correct DB role.
    "PLATFORM_ADMIN_KEYCLOAK_ID":       "credebl-client",
    "PLATFORM_ADMIN_KEYCLOAK_SECRET":   e("KEYCLOAK_CLIENT_SECRET"),
    "KEYCLOAK_PUBLIC_URL":              e("KEYCLOAK_PUBLIC_URL"),
    "PLATFORM_ADMIN_INITIAL_PASSWORD":  e("PLATFORM_ADMIN_INITIAL_PASSWORD"),
    "MINIO_ROOT_PASSWORD":              e("MINIO_ROOT_PASSWORD"),
    "AWS_ACCESS_KEY_ID":                e("AWS_ACCESS_KEY_ID"),
    "AWS_SECRET_ACCESS_KEY":            e("AWS_SECRET_ACCESS_KEY"),
    # Aliases used by the utility service (reads AWS_ACCESS_KEY, not AWS_ACCESS_KEY_ID)
    "AWS_ACCESS_KEY":                   e("AWS_ACCESS_KEY_ID"),
    "AWS_SECRET_KEY":                   e("AWS_SECRET_ACCESS_KEY"),
    "AWS_PUBLIC_ACCESS_KEY":            e("AWS_ACCESS_KEY_ID"),
    "AWS_PUBLIC_SECRET_KEY":            e("AWS_SECRET_ACCESS_KEY"),
    "AWS_PUBLIC_REGION":                "us-east-1",
    "AWS_S3_STOREOBJECT_ACCESS_KEY":    e("AWS_ACCESS_KEY_ID"),
    "AWS_S3_STOREOBJECT_SECRET_KEY":    e("AWS_SECRET_ACCESS_KEY"),
    "AWS_S3_STOREOBJECT_ENDPOINT":      "http://minio:9000",
    "PLATFORM_SEED":                    e("PLATFORM_SEED"),
    "PLATFORM_WALLET_NAME":             e("PLATFORM_WALLET_NAME"),
    "PLATFORM_WALLET_PASSWORD":         e("PLATFORM_WALLET_PASSWORD"),
    "AGENT_API_KEY":                    e("AGENT_API_KEY"),
    # 172.17.0.1 = docker0 bridge gateway. The spawned Credo container runs on
    # Docker's default bridge network (not credebl-net), so it cannot resolve
    # the hostname 'postgres'. The public VPS IP is also unreliable because many
    # VPS providers block self-connections on the public IP (loopback via NIC).
    # 172.17.0.1 is always reachable from any default-bridge container and routes
    # through to the host's published port 5432.
    "WALLET_STORAGE_HOST":              "172.17.0.1",
    "WALLET_STORAGE_PASSWORD":          e("POSTGRES_PASSWORD"),
    "JWT_SECRET":                       e("JWT_SECRET"),
    "NEXTAUTH_SECRET":                  e("NEXTAUTH_SECRET"),
    "JWT_TOKEN_SECRET":                 e("JWT_TOKEN_SECRET"),
    "SCHEMA_FILE_SERVER_TOKEN":         e("SCHEMA_FILE_SERVER_TOKEN"),
    "CRYPTO_PRIVATE_KEY":               e("CRYPTO_PRIVATE_KEY"),
    "ADMIN_KEYCLOAK_ID":                e("ADMIN_KEYCLOAK_ID"),
    "ADMIN_KEYCLOAK_SECRET":            e("ADMIN_KEYCLOAK_SECRET"),
    "NEXTAUTH_COOKIE_DOMAIN":           "",
    "PLATFORM_ADMIN_EMAIL":             e("PLATFORM_ADMIN_EMAIL"),
    "API_ENDPOINT":                     e("API_ENDPOINT"),
    "VPS_IP":                           e("VPS_HOST"),
    "PLATFORM_WEB_URL":                 e("PLATFORM_WEB_URL"),
    "FRONT_END_URL":                    e("PLATFORM_WEB_URL"),
    "STUDIO_URL":                       e("STUDIO_URL"),
    "SOCKET_HOST":                      e("SOCKET_HOST"),
    "ENABLE_CORS_IP_LIST":              e("ENABLE_CORS_IP_LIST"),
    "APP_PROTOCOL":                     e("PROTOCOL"),
    "DEEPLINK_DOMAIN":                  e("DEEPLINK_DOMAIN"),
    # SHORTENED_URL_DOMAIN is intentionally empty — utility service builds /default/{uuid}
    # which gets concatenated directly onto DEEPLINK_DOMAIN
    "SHORTENED_URL_DOMAIN":             "",
    # Email provider — smtp routes through Mailpit (no external calls), sendgrid uses real API
    "EMAIL_PROVIDER":                   "sendgrid" if e("USE_SENDGRID") == "true" else "smtp",
    "SENDGRID_API_KEY":                 e("SENDGRID_API_KEY_VAL"),
    "EMAIL_FROM":                       e("EMAIL_FROM_VAL"),
    # SMTP settings are only active when EMAIL_PROVIDER=smtp (Mailpit mode)
    "SMTP_HOST":                        "mailpit" if e("USE_SENDGRID") != "true" else "",
    "SMTP_PORT":                        "1025"    if e("USE_SENDGRID") != "true" else "",
    "SMTP_USER":                        "mailpit" if e("USE_SENDGRID") != "true" else "",
    "SMTP_PASS":                        "mailpit" if e("USE_SENDGRID") != "true" else "",
    "SMTP_SECURE":                      "false",
    "MOBILE_APP":                       '"Inji Wallet"',
    "MOBILE_APP_NAME":                  '"Inji Wallet"',
    "MOBILE_APP_DOWNLOAD_URL":          "https://inji.mosip.io",
    "PLAY_STORE_DOWNLOAD_LINK":         "https://play.google.com/store/apps/details?id=io.mosip.residentapp",
}

for key, value in replacements.items():
    pattern = re.compile(rf"^{re.escape(key)}=.*$", re.MULTILINE)
    text = pattern.sub(f"{key}={value}", text)

# Catch any remaining placeholder tokens not covered by key substitution above
text = text.replace("YOUR_VPS_IP", e("VPS_HOST"))
text = text.replace("YOUR_POSTGRES_PASSWORD", e("POSTGRES_PASSWORD"))

env_file.write_text(text, encoding="utf-8")

# Update credebl-master-table.json with VPS host values and the chosen admin email.
# platformAdminData.email/username must match PLATFORM_ADMIN_EMAIL so the seed creates
# the right user — the bootstrap then links that DB user to the Keycloak user by the same email.
config = json.loads(master_table.read_text(encoding="utf-8"))

pc = config.setdefault("platformConfigData", {})
pc["externalIp"]      = e("VPS_PUBLIC_HOST")
pc["inboundEndpoint"] = e("VPS_PUBLIC_HOST")
# When HTTPS + VPS_DOMAIN: API is on port 443 via nginx (no explicit port in URL)
api_port = "" if e("PROTOCOL") == "https" else ":5000"
pc["apiEndpoint"]     = f"{e('PROTOCOL')}://{e('VPS_PUBLIC_HOST')}{api_port}"
config["platformConfigData"] = pc

pa = config.setdefault("platformAdminData", {})
pa["email"]    = e("PLATFORM_ADMIN_EMAIL")
pa["username"] = e("PLATFORM_ADMIN_EMAIL")
config["platformAdminData"] = pa

master_table.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
PY

echo "  .env written:          $ENV_FILE"
echo "  master-table updated:  $MASTER_TABLE"

write_agent_runtime_env
echo "  agent runtime env:     $AGENT_RUNTIME_ENV_FILE"

# =============================================================================
# CREDENTIALS REPORT — print before any Docker operation
# =============================================================================

echo
echo "============================================================"
echo " CREDENTIALS REPORT — save this before continuing"
echo "============================================================"
printf " %-28s %s\n" "VPS host:"               "$VPS_HOST"
printf " %-28s %s\n" "Keycloak host:"           "$KEYCLOAK_HOST"
printf " %-28s %s\n" "Keycloak public URL:"     "$KEYCLOAK_PUBLIC_URL"
printf " %-28s %s\n" "Studio URL:"              "$STUDIO_URL"
printf " %-28s %s\n" "API URL:"                 "$PLATFORM_WEB_URL"
echo " ----------------------------------------------------------"
printf " %-28s %s\n" "Studio email:"            "$PLATFORM_ADMIN_EMAIL"
printf " %-28s %s\n" "Studio password:"         "$PLATFORM_ADMIN_INITIAL_PASSWORD"
echo " ----------------------------------------------------------"
printf " %-28s %s\n" "Postgres password:"       "$POSTGRES_PASSWORD"
printf " %-28s %s\n" "Keycloak admin password:" "$KEYCLOAK_ADMIN_PASSWORD"
printf " %-28s %s\n" "Keycloak client secret:"  "$KEYCLOAK_CLIENT_SECRET"
printf " %-28s %s\n" "MinIO root password:"     "$MINIO_ROOT_PASSWORD"
printf " %-28s %s\n" "MinIO access key ID:"     "$AWS_ACCESS_KEY_ID"
printf " %-28s %s\n" "MinIO secret key:"        "$AWS_SECRET_ACCESS_KEY"
printf " %-28s %s\n" "Platform seed:"           "$PLATFORM_SEED"
printf " %-28s %s\n" "Wallet password:"         "$PLATFORM_WALLET_PASSWORD"
printf " %-28s %s\n" "Agent API key:"           "$AGENT_API_KEY"
printf " %-28s %s\n" "JWT secret:"              "$JWT_SECRET"
printf " %-28s %s\n" "NextAuth secret:"         "$NEXTAUTH_SECRET"
printf " %-28s %s\n" "JWT token secret:"        "$JWT_TOKEN_SECRET"
printf " %-28s %s\n" "Crypto private key:"      "$CRYPTO_PRIVATE_KEY"
echo " ----------------------------------------------------------"
if [ "$USE_SENDGRID" = "true" ]; then
  printf " %-28s %s\n" "Email provider:"          "SendGrid"
  printf " %-28s %s\n" "SendGrid API key:"        "$SENDGRID_API_KEY_VAL"
  printf " %-28s %s\n" "Email FROM:"              "$EMAIL_FROM_VAL"
else
  printf " %-28s %s\n" "Email provider:"          "Mailpit (local, port 8025)"
  printf " %-28s %s\n" "Mailpit web UI:"          "http://${VPS_HOST}:8025"
  printf " %-28s %s\n" "Email FROM:"              "$EMAIL_FROM_VAL"
fi
echo "============================================================"
echo

# =============================================================================
# DOCKER DEPLOY
# =============================================================================

cd "$CREDEBL_DIR"
mkdir -p .agent-runtime/agent-config .agent-runtime/token .agent-runtime/endpoints

# `docker compose down -v` does NOT remove built images — only containers and
# volumes. So the Studio image survives a full reset and can be reused, saving
# several minutes of Next.js build time. Build args (NEXTAUTH_SECRET, API_ENDPOINT,
# etc.) are baked in at build time — if the VPS IP or secrets changed, force a
# rebuild by answering N to the question below.
# docker compose names a build-only service image as <project>-<service>.
# When run from the credebl/ directory the project name is "credebl", so the
# Studio image is always "credebl-studio". Check for that specific image name.
STUDIO_IMAGE="credebl-studio"
SKIP_STUDIO_BUILD=false
if docker image inspect "$STUDIO_IMAGE" >/dev/null 2>&1; then
  echo
  if ask_yes_no "Studio image already exists. Skip rebuild? (answer N if VPS IP or secrets changed)" "Y"; then
    SKIP_STUDIO_BUILD=true
    echo "  Will reuse existing Studio image."
  else
    echo "  Will rebuild Studio image."
  fi
fi

if ask_yes_no "Clean reset first? (docker compose down -v --remove-orphans)" "Y"; then
  docker compose down -v --remove-orphans
fi

# Remove any stale Credo controller containers left over from previous deployments.
# These are spawned by agent-provisioning via `docker run` (outside compose scope),
# so `docker compose down` never removes them. If they hold ports 8001-9099, the
# new spin-up will fail with "port is already allocated".
echo
echo "Cleaning up stale Credo controller containers from previous deployments..."
purge_stale_credo_containers

echo
echo "Pulling images..."
docker compose pull

echo
echo "Starting the stack..."
if [ "$SKIP_STUDIO_BUILD" = "true" ]; then
  # Image already exists — skip the Next.js build entirely.
  docker compose up -d --no-build
else
  # Build Studio first (docker compose pull skips build-only services, so the
  # image doesn't exist yet). Then bring up all services without rebuilding.
  echo "Building Studio image (this may take several minutes)..."
  docker compose build studio
  docker compose up -d --no-build
fi

ensure_minio_setup

echo
echo "Ensuring email branding assets..."
ensure_brand_logo

apply_container_patches

ensure_platform_admin_shared_agent

# Re-apply Credo patches now that the platform admin agent container is running.
echo -n "  Patching Credo CredentialEvents (post-agent-spawn): "
patch_credo_credential_events
echo -n "  Patching Credo ProofEvents (post-agent-spawn): "
patch_credo_proof_events

ensure_platform_admin_tenant

# When using SendGrid, the seed populates platform_config.emailFrom with a default
# value that won't be accepted by SendGrid (unverified domain). Update it now.
[ "$USE_SENDGRID" = "true" ] && ensure_sendgrid_from_address

# Grant 'owner' org role to platform admin so org-scoped endpoints pass the
# OrgRolesGuard. CREDEBL's guard on GET /orgs/:orgId and POST /orgs/:orgId/agents/wallet
# requires [owner, admin, ...] — 'platform_admin' alone is not in those lists.
# The platform_admin bypass in the guard only fires when there is NO orgId in
# the request (admin-only endpoints). All org CRUD endpoints have :orgId in the URL.
echo
echo "Granting owner role to platform admin user..."
docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
  psql -U credebl -d credebl -v ON_ERROR_STOP=1 -c "
INSERT INTO user_org_roles (id, \"userId\", \"orgId\", \"orgRoleId\")
SELECT gen_random_uuid(), uor.\"userId\", uor.\"orgId\", r.id
FROM user_org_roles uor
JOIN \"user\" u       ON u.id   = uor.\"userId\"
JOIN org_roles src   ON src.id = uor.\"orgRoleId\" AND src.name = 'platform_admin'
CROSS JOIN (SELECT id FROM org_roles WHERE name = 'owner') r
WHERE u.email = '${PLATFORM_ADMIN_EMAIL}'
  AND NOT EXISTS (
    SELECT 1 FROM user_org_roles x
    WHERE x.\"userId\"    = uor.\"userId\"
      AND x.\"orgId\"     = uor.\"orgId\"
      AND x.\"orgRoleId\" = r.id
  );
" >/dev/null
echo "  Platform admin owner role ensured."

# =============================================================================
# SSL / HTTPS SETUP (only when requested)
# =============================================================================

if [ "$ENABLE_SSL" = "true" ]; then
  echo
  _ssl_label="$SSL_KEYCLOAK_DOMAIN"
  [ -n "$SSL_VPS_DOMAIN" ] && _ssl_label="$_ssl_label + $SSL_VPS_DOMAIN"
  echo "Setting up HTTPS certificates for: $_ssl_label ..."
  echo "Note: requires sudo to install nginx and run certbot."

  _ssl_args=(
    --domain      "$SSL_KEYCLOAK_DOMAIN"
    --email       "$PLATFORM_ADMIN_EMAIL"
    --credebl-dir "$CREDEBL_DIR"
  )
  [ -n "$SSL_VPS_DOMAIN" ] && _ssl_args+=(--vps-domain "$SSL_VPS_DOMAIN")

  if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    sudo bash "$SCRIPT_DIR/setup-keycloak-https.sh" "${_ssl_args[@]}"
  else
    bash "$SCRIPT_DIR/setup-keycloak-https.sh" "${_ssl_args[@]}"
  fi
fi

# =============================================================================
# HEALTH CHECK + FINAL SUMMARY
# =============================================================================

echo
bash "$SCRIPT_DIR/health-check.sh"

echo
echo "============================================================"
echo " Deployment complete"
echo "============================================================"
printf " %-20s %s\n" "Studio:" "$STUDIO_URL"
printf " %-20s %s\n" "Email:"  "$PLATFORM_ADMIN_EMAIL"
printf " %-20s %s\n" "Password:" "$PLATFORM_ADMIN_INITIAL_PASSWORD"
echo "============================================================"
