#!/usr/bin/env bash
# =============================================================================
# CDPI PoC — CREDEBL single-path initializer
# -----------------------------------------------------------------------------
# Single entry point for a complete CREDEBL deployment.
# Asks only 4-5 essential questions; all secrets are generated automatically.
#
# Usage:
#   bash scripts/init-credebl.sh
# =============================================================================

set -euo pipefail

# --- Paths -------------------------------------------------------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
CREDEBL_DIR="$REPO_DIR/credebl"
ENV_TEMPLATE="$CREDEBL_DIR/.env.example"
ENV_FILE="$CREDEBL_DIR/.env"
MASTER_TABLE="$CREDEBL_DIR/config/credebl-master-table.json"
AGENT_RUNTIME_DIR="$CREDEBL_DIR/.agent-runtime"
AGENT_RUNTIME_ENV_FILE="$AGENT_RUNTIME_DIR/agent.env"

# --- Utility functions -------------------------------------------------------

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || { echo "Error: required command '$1' not found." >&2; exit 1; }
}

# Strip protocol and trailing slashes from a host input
sanitize_host() {
  local v
  v="$(printf '%s' "$1" | sed 's/^ *//;s/ *$//')"
  v="${v#http://}"
  v="${v#https://}"
  v="${v%%/*}"
  printf '%s' "$v"
}

ask() {
  local prompt="$1"
  local default="${2:-}"
  local secret="${3:-false}"
  local value

  while true; do
    if [ "$secret" = "true" ]; then
      [ -n "$default" ] \
        && printf "%s [press Enter for auto-generated value]: " "$prompt" >&2 \
        || printf "%s: " "$prompt" >&2
      read -r -s value
      printf "\n" >&2
    else
      [ -n "$default" ] \
        && printf "%s [%s]: " "$prompt" "$default" >&2 \
        || printf "%s: " "$prompt" >&2
      read -r value
    fi

    [ -z "$value" ] && value="$default"
    [ -n "$value" ] && { printf '%s' "$value"; return 0; }
    echo "A value is required." >&2
  done
}

ask_yes_no() {
  local prompt="$1"
  local default="${2:-N}"
  local reply suffix="[y/N]"
  [ "$default" = "Y" ] && suffix="[Y/n]"

  while true; do
    printf "%s %s: " "$prompt" "$suffix" >&2
    read -r reply
    reply="$(printf '%s' "$reply" | sed 's/^ *//;s/ *$//')"
    [ -z "$reply" ] && reply="$default"
    case "$reply" in
      [Yy]|[Yy][Ee][Ss]) return 0 ;;
      [Nn]|[Nn][Oo])     return 1 ;;
    esac
    echo "Please answer yes or no." >&2
  done
}

# Generate an HS256 JWT signed with JWT_TOKEN_SECRET for schema-file-server
generate_hs256_jwt() {
  python3 - "$1" "$2" <<'PY'
import base64, hashlib, hmac, json, sys, time

secret_input, issuer = sys.argv[1], sys.argv[2]
now = int(time.time())

try:
    secret = base64.b64decode(secret_input, validate=True)
    if not secret:
        secret = secret_input.encode("utf-8")
except Exception:
    secret = secret_input.encode("utf-8")

def b64url(data):
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")

h = b64url(json.dumps({"alg": "HS256", "typ": "JWT"}, separators=(",", ":")).encode())
p = b64url(json.dumps(
    {"iss": issuer, "sub": "schema-file-server", "iat": now, "exp": now + 315360000},
    separators=(",", ":"),
).encode())
sig = b64url(hmac.new(secret, f"{h}.{p}".encode("ascii"), hashlib.sha256).digest())
print(f"{h}.{p}.{sig}")
PY
}

write_agent_runtime_env() {
  mkdir -p "$AGENT_RUNTIME_DIR/agent-config" "$AGENT_RUNTIME_DIR/token" "$AGENT_RUNTIME_DIR/endpoints"

  # Guard against a previous run that left agent.env as a directory
  [ -d "$AGENT_RUNTIME_ENV_FILE" ] && rm -rf "$AGENT_RUNTIME_ENV_FILE"

  cat > "$AGENT_RUNTIME_ENV_FILE" <<EOF
# Generated by scripts/init-credebl.sh — do not edit manually
LEDGER_URL=http://test.bcovrin.vonx.io
GENESIS_URL=http://test.bcovrin.vonx.io/genesis
TAILS_FILE_SERVER=https://tails.vonx.io
AGENT_HTTP_URL=http://${VPS_HOST}
AGENT_WS_URL=ws://${VPS_HOST}
CONNECT_TIMEOUT=10
MAX_CONNECTIONS=1000
IDLE_TIMEOUT=30000
SESSION_ACQUIRE_TIMEOUT=2147483647
SESSION_LIMIT=2147483647
INMEMORY_LRU_CACHE_LIMIT=2147483647
TRUST_SERVICE_AUTH_TYPE=NoAuth
TRUST_LIST_URL=https://example.com/trust-list.json
EOF
}

wait_for_container_state() {
  local name="$1" pattern="$2" attempts="${3:-60}" i=1
  while [ "$i" -le "$attempts" ]; do
    docker inspect --format='{{.State.Status}} {{.State.ExitCode}}' "$name" 2>/dev/null \
      | grep -Eqi "$pattern" && return 0
    sleep 2
    i=$((i + 1))
  done
  return 1
}

ensure_minio_setup() {
  echo
  echo "Ensuring MinIO buckets and access keys are initialized..."
  docker compose up -d minio >/dev/null

  local attempt=1
  while [ "$attempt" -le 5 ]; do
    docker compose rm -sf minio-setup >/dev/null 2>&1 || true
    if docker compose up --no-deps minio-setup \
       && wait_for_container_state "credebl-minio-setup" '^exited 0$' 10; then
      echo "MinIO setup complete."
      return 0
    fi
    echo "  MinIO setup failed (attempt $attempt/5). Retrying..."
    attempt=$((attempt + 1))
    sleep 3
  done

  echo "Error: minio-setup did not complete successfully." >&2
  echo "Inspect with: docker compose logs --tail=200 minio-setup" >&2
  return 1
}

platform_admin_shared_agent_ready() {
  local row status endpoint token_url
  row="$(docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -Atqc "
      SELECT COALESCE(oa.\"agentSpinUpStatus\"::text, ''),
             COALESCE(oa.\"agentEndPoint\", '')
      FROM organisation o
      LEFT JOIN org_agents oa ON oa.\"orgId\" = o.id
      WHERE o.name = 'Platform-admin'
      LIMIT 1;" 2>/dev/null | tr -d '\r')"

  status="${row%%|*}"
  endpoint="${row#*|}"

  [ "$status" != "2" ] && return 1
  [ -z "$endpoint" ] || [ "$endpoint" = "http://" ] || [ "$endpoint" = "https://" ] && return 1

  [[ "$endpoint" =~ ^https?:// ]] \
    && token_url="${endpoint%/}/agent/token" \
    || token_url="http://${endpoint}/agent/token"

  curl -sf --max-time 8 -X POST -H "Authorization: $AGENT_API_KEY" "$token_url" >/dev/null
}

# Kill all Credo controller containers that were spawned outside of docker compose.
# Uses two complementary strategies because the image-ancestor filter alone is unreliable:
#   1. Ancestor filter — works when the image tag hasn't changed.
#   2. Name pattern  — agent-provisioning always names these containers as
#      "{org-uuid}_{ContainerName}" (e.g. "c1f8a28f-71a3-..._Platform-admin").
#      Matching on the UUID prefix catches them regardless of image tag or pull history.
purge_stale_credo_containers() {
  local found=0 names

  # Strategy 1: by image ancestor
  names=$(docker ps -a \
    --filter "ancestor=ghcr.io/credebl/credo-controller:latest" \
    --format "{{.Names}}" 2>/dev/null || true)
  if [ -n "$names" ]; then
    echo "$names" | xargs docker rm -f 2>/dev/null || true
    echo "  Removed by image: $(printf '%s' "$names" | tr '\n' ' ')"
    found=1
  fi

  # Strategy 2: by name pattern — agent-provisioning names containers as
  # "{org-uuid}_{ContainerName}" (e.g. "c1f8a28f-..._Platform-admin").
  # Avoid grep-in-pipeline inside $() — with set -euo pipefail, grep's exit 1
  # (no match) can escape the || true guard and kill the script. Use a while-read
  # loop with bash regex instead, which has no pipeline exit-code hazard.
  names=""
  while IFS= read -r cname; do
    [[ "$cname" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}_ ]] \
      && names="${names}${cname}"$'\n' || true
  done < <(docker ps -a --format "{{.Names}}" 2>/dev/null || true)
  if [ -n "$names" ]; then
    printf '%s' "$names" | xargs docker rm -f 2>/dev/null || true
    echo "  Removed by name pattern: $(printf '%s' "$names" | tr '\n' ' ')"
    found=1
  fi

  [ "$found" -eq 0 ] && echo "  No stale Credo containers found." || true
}

clear_stale_platform_admin_agent() {
  # Remove the incomplete org_agents record so agent-service will try again.
  docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -v ON_ERROR_STOP=1 -c "
      DELETE FROM org_agents oa
      USING organisation o
      WHERE oa.\"orgId\" = o.id
        AND o.name = 'Platform-admin'
        AND (
          oa.\"agentSpinUpStatus\" <> 2
          OR COALESCE(oa.\"agentEndPoint\", '') = ''
        );" >/dev/null

  # Credo (askar) creates a separate PostgreSQL database named after the wallet.
  # If a previous provision attempt failed mid-way, that database still exists and
  # the next attempt throws "Your wallet is already been created". Drop it so the
  # next agent-service startup can provision the wallet cleanly from scratch.
  docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d postgres -c "
      SELECT pg_terminate_backend(pid)
      FROM pg_stat_activity
      WHERE datname = '${PLATFORM_WALLET_NAME}';
      DROP DATABASE IF EXISTS \"${PLATFORM_WALLET_NAME}\";" >/dev/null 2>&1 || true
}

# Handles the "container running but endpoint never written" race condition.
# CREDEBL's agent-service can restart mid-provisioning, lose the NATS response from
# agent-provisioning, and leave agentSpinUpStatus=1 with an empty agentEndPoint even
# though the Credo container is healthy. This function detects that state, extracts the
# admin port from the running container, tests it, and patches the DB directly.
recover_orphan_running_agent() {
  local container port endpoint

  # Look for a running (not exited) Credo container whose name matches the UUID pattern
  container=$(docker ps --format "{{.Names}}" 2>/dev/null \
    | grep -E "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}_Platform-admin$" \
    | head -1 || true)
  [ -z "$container" ] && return 1

  echo "  Found running agent container: $container"

  # Extract the host-side admin port (8xxx range — that's the Credo REST API port)
  # `docker port` output: "8006/tcp -> 0.0.0.0:8006" — $NF is always the host port
  port=$(docker port "$container" 2>/dev/null \
    | awk -F'[/: ]' '$1+0 >= 8000 && $1+0 < 9000 { print $NF; exit }')
  [ -z "$port" ] && { echo "  Could not determine admin port for $container"; return 1; }

  endpoint="http://${VPS_HOST}:${port}"
  echo "  Testing agent endpoint: ${endpoint}/agent/token"

  if ! curl -sf --max-time 10 -X POST \
      -H "Authorization: $AGENT_API_KEY" "${endpoint}/agent/token" >/dev/null; then
    echo "  Agent container is running but not responding on ${endpoint}"
    return 1
  fi

  echo "  Agent is responding. Patching DB record (status=2, endpoint=${endpoint})..."
  docker compose exec -T postgres env PGPASSWORD="$POSTGRES_PASSWORD" \
    psql -U credebl -d credebl -v ON_ERROR_STOP=1 -c "
      UPDATE org_agents oa
      SET \"agentSpinUpStatus\" = 2,
          \"agentEndPoint\"     = '${endpoint}'
      FROM organisation o
      WHERE oa.\"orgId\" = o.id
        AND o.name = 'Platform-admin';" >/dev/null

  echo "  Restarting agent-service so it picks up the updated endpoint..."
  docker compose restart agent-service >/dev/null
  sleep 20
}

ensure_platform_admin_shared_agent() {
  echo
  echo "Ensuring platform-admin shared agent is initialized..."

  if ! wait_for_container_state "credebl-platform-admin-bootstrap" '^exited 0$' 90; then
    echo "Error: platform-admin-bootstrap did not complete." >&2
    echo "Inspect with: docker compose logs --tail=200 platform-admin-bootstrap" >&2
    return 1
  fi

  local attempt=1
  while [ "$attempt" -le 12 ]; do
    if platform_admin_shared_agent_ready; then
      echo "Platform-admin shared agent is ready."
      return 0
    fi

    echo "  Not ready yet (attempt $attempt/12). Clearing stale state and restarting..."
    clear_stale_platform_admin_agent || true
    purge_stale_credo_containers
    docker compose up -d cloud-wallet >/dev/null
    docker compose restart agent-provisioning agent-service >/dev/null
    # The full provision cycle takes ~40s: Nest startup + Prisma migrate + wallet init + agent start.
    # Waiting only 10s means we restart again before the previous attempt finishes, making it worse.
    echo "  Waiting 50s for provisioning cycle to complete..."
    sleep 50
    attempt=$((attempt + 1))
  done

  # All retries exhausted. The Credo container may be running but the endpoint was never
  # written to the DB (race condition: agent-service restarted mid-NATS response). Try
  # to recover by detecting and patching the orphan container before giving up.
  echo "  Retries exhausted. Attempting orphan-container recovery..."
  if recover_orphan_running_agent && platform_admin_shared_agent_ready; then
    echo "Platform-admin shared agent is ready (recovered from orphan container)."
    return 0
  fi

  echo "Error: platform-admin shared agent did not reach ready state." >&2
  echo "Inspect with: docker compose logs --tail=200 agent-service agent-provisioning" >&2
  return 1
}

# =============================================================================
# PREREQUISITE CHECKS
# =============================================================================

require_cmd docker
require_cmd python3
require_cmd openssl
require_cmd curl

if ! docker info >/dev/null 2>&1; then
  echo "Error: Docker is not running or this user cannot access it." >&2
  exit 1
fi

[ -f "$ENV_TEMPLATE" ] || { echo "Error: template not found at $ENV_TEMPLATE" >&2; exit 1; }
[ -f "$MASTER_TABLE" ]  || { echo "Error: seed config not found at $MASTER_TABLE" >&2; exit 1; }

# =============================================================================
# INTERACTIVE PROMPTS — 4 questions, 5 if SSL is requested
# =============================================================================

cat <<'BANNER'
============================================================
 CDPI PoC — CREDEBL initializer
============================================================
 Answers 4 questions. All secrets are auto-generated and
 printed in full at the end — save that report securely.
============================================================
BANNER
echo

# 1. VPS host — autodetect with fallback
DETECTED_IP="$(curl -4 -fsS --max-time 5 ifconfig.me 2>/dev/null \
  || hostname -I 2>/dev/null | awk '{print $1}' \
  || true)"
DETECTED_IP="$(sanitize_host "${DETECTED_IP:-}")"

VPS_HOST="$(ask "VPS public IP or hostname (without http://)" "$DETECTED_IP")"
VPS_HOST="$(sanitize_host "$VPS_HOST")"

# 2. Keycloak host — default to same VPS but can be different
KEYCLOAK_HOST="$(ask "Keycloak host (press Enter if same as VPS)" "$VPS_HOST")"
KEYCLOAK_HOST="$(sanitize_host "$KEYCLOAK_HOST")"

# 3. Platform admin email
PLATFORM_ADMIN_EMAIL="$(ask "Platform admin email" "admin@cdpi-poc.local")"

# 4. SSL / Let's Encrypt
ENABLE_SSL=false
SSL_KEYCLOAK_DOMAIN=""
SSL_VPS_DOMAIN=""
if ask_yes_no "Enable HTTPS with Let's Encrypt certificates?" "N"; then
  ENABLE_SSL=true

  # 5a. Keycloak domain — suggest KEYCLOAK_HOST only if it looks like an FQDN, not a raw IP
  _kc_default="$KEYCLOAK_HOST"
  printf '%s' "$KEYCLOAK_HOST" | grep -Eq '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' && _kc_default=""
  SSL_KEYCLOAK_DOMAIN="$(ask "Keycloak domain for the SSL certificate (DNS must point to this VPS)" "$_kc_default")"
  SSL_KEYCLOAK_DOMAIN="$(sanitize_host "$SSL_KEYCLOAK_DOMAIN")"

  # 5b. General VPS domain (optional) — for API Gateway / Studio; skipped when same as Keycloak domain
  _vps_default="$VPS_HOST"
  printf '%s' "$VPS_HOST" | grep -Eq '^[0-9]{1,3}(\.[0-9]{1,3}){3}$' && _vps_default=""
  if [ -z "$_vps_default" ] || [ "$_vps_default" != "$SSL_KEYCLOAK_DOMAIN" ]; then
    if ask_yes_no "Also issue an SSL certificate for the general VPS domain (API / Studio)?" "N"; then
      SSL_VPS_DOMAIN="$(ask "General VPS domain for the SSL certificate (DNS must point to this VPS)" "$_vps_default")"
      SSL_VPS_DOMAIN="$(sanitize_host "$SSL_VPS_DOMAIN")"
    fi
  fi
fi

# =============================================================================
# GENERATE ALL SECRETS
# =============================================================================

POSTGRES_PASSWORD="$(openssl rand -hex 16)"
KEYCLOAK_ADMIN_PASSWORD="$(openssl rand -hex 16)"
KEYCLOAK_CLIENT_SECRET="$(openssl rand -hex 32)"
PLATFORM_ADMIN_INITIAL_PASSWORD="$(openssl rand -hex 8)"   # 16 hex chars — easy to type
MINIO_ROOT_PASSWORD="$(openssl rand -hex 16)"
AWS_ACCESS_KEY_ID="credebls3"
AWS_SECRET_ACCESS_KEY="$(openssl rand -hex 16)"
PLATFORM_SEED="$(openssl rand -hex 16)"
PLATFORM_WALLET_NAME="platformadminwallet"
PLATFORM_WALLET_PASSWORD="$(openssl rand -hex 16)"
AGENT_API_KEY="$(openssl rand -hex 32)"
JWT_SECRET="$(openssl rand -hex 32)"
NEXTAUTH_SECRET="$(openssl rand -hex 32)"
# base64 required — schema-file-server decodes it before signing JWTs
JWT_TOKEN_SECRET="$(openssl rand -base64 32 | tr -d '\n')"
# CRYPTO_PRIVATE_KEY must match platformAdminData.password encryption in master-table.json
# Keep the PoC default so the seeded admin password decrypts correctly on first boot
CRYPTO_PRIVATE_KEY="cdpi-poc-crypto-key-change-me"
# Keycloak admin client credentials used by the seed to call the Keycloak Admin REST API.
# ADMIN_KEYCLOAK_ID   = client_id  of the admin client (same as PLATFORM_ADMIN_KEYCLOAK_ID)
# ADMIN_KEYCLOAK_SECRET = client_secret of that client (same as KEYCLOAK_CLIENT_SECRET)
# Required by CREDEBL seed >= v1.x. Our bootstrap handles the 409 (user already exists)
# gracefully, so seed + bootstrap can both run without conflict.
ADMIN_KEYCLOAK_ID="adminClient"
ADMIN_KEYCLOAK_SECRET="$KEYCLOAK_CLIENT_SECRET"

# JWT signed with JWT_TOKEN_SECRET — required for W3C / did:web / did:key schema creation
SCHEMA_FILE_SERVER_TOKEN="$(generate_hs256_jwt "$JWT_TOKEN_SECRET" "Credebl")"

# =============================================================================
# DERIVE ALL URLS
# =============================================================================

PROTOCOL="http"

# Internal URLs — CREDEBL microservices reach Keycloak inside Docker
if [ "$KEYCLOAK_HOST" = "$VPS_HOST" ]; then
  # Same machine: use Docker service name for internal traffic
  KEYCLOAK_DOMAIN_INTERNAL="http://keycloak:8080/"
  KEYCLOAK_ADMIN_URL_INTERNAL="http://keycloak:8080"
else
  # External Keycloak: use its host directly
  KEYCLOAK_DOMAIN_INTERNAL="http://${KEYCLOAK_HOST}:8080/"
  KEYCLOAK_ADMIN_URL_INTERNAL="http://${KEYCLOAK_HOST}:8080"
fi

# Public URL — used by wallets and browsers; becomes HTTPS when SSL is enabled
if [ "$ENABLE_SSL" = "true" ]; then
  KEYCLOAK_PUBLIC_URL="https://${SSL_KEYCLOAK_DOMAIN}"
else
  KEYCLOAK_PUBLIC_URL="http://${KEYCLOAK_HOST}:8080"
fi

# API and Studio always use HTTP on their ports for the PoC
# (SSL is only for the Keycloak OIDC endpoint via nginx reverse proxy)
STUDIO_URL="${PROTOCOL}://${VPS_HOST}:3000"
API_ENDPOINT="${VPS_HOST}:5000"           # bare host:port — no protocol prefix
PLATFORM_WEB_URL="${PROTOCOL}://${VPS_HOST}:5000"
SOCKET_HOST="${PROTOCOL}://${VPS_HOST}:5000"
ENABLE_CORS_IP_LIST="${STUDIO_URL},http://localhost:3000,http://127.0.0.1:3000"

# =============================================================================
# WRITE .env FROM TEMPLATE
# =============================================================================

if [ -f "$ENV_FILE" ]; then
  if ! ask_yes_no "Existing $ENV_FILE found. Overwrite it?" "N"; then
    echo "Aborted. Existing .env left untouched."
    exit 0
  fi
fi

export ENV_TEMPLATE ENV_FILE MASTER_TABLE \
  POSTGRES_PASSWORD KEYCLOAK_ADMIN_PASSWORD KEYCLOAK_CLIENT_SECRET \
  PLATFORM_ADMIN_INITIAL_PASSWORD MINIO_ROOT_PASSWORD \
  AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY \
  PLATFORM_SEED PLATFORM_WALLET_NAME PLATFORM_WALLET_PASSWORD \
  AGENT_API_KEY JWT_SECRET NEXTAUTH_SECRET JWT_TOKEN_SECRET \
  SCHEMA_FILE_SERVER_TOKEN CRYPTO_PRIVATE_KEY ADMIN_KEYCLOAK_ID ADMIN_KEYCLOAK_SECRET \
  PLATFORM_ADMIN_EMAIL VPS_HOST KEYCLOAK_HOST PROTOCOL \
  KEYCLOAK_DOMAIN_INTERNAL KEYCLOAK_ADMIN_URL_INTERNAL KEYCLOAK_PUBLIC_URL \
  STUDIO_URL API_ENDPOINT PLATFORM_WEB_URL SOCKET_HOST ENABLE_CORS_IP_LIST

python3 <<'PY'
import json, os, re
from pathlib import Path

env_template = Path(os.environ["ENV_TEMPLATE"])
env_file     = Path(os.environ["ENV_FILE"])
master_table = Path(os.environ["MASTER_TABLE"])
e = os.environ.__getitem__

text = env_template.read_text(encoding="utf-8")

# Each entry replaces the matching KEY=... line in the template.
# Derived compound values (DATABASE_URL, etc.) are computed here.
replacements = {
    "POSTGRES_PASSWORD":                e("POSTGRES_PASSWORD"),
    "DATABASE_URL":                     f"postgresql://credebl:{e('POSTGRES_PASSWORD')}@postgres:5432/credebl",
    "POOL_DATABASE_URL":                f"postgresql://credebl:{e('POSTGRES_PASSWORD')}@postgres:5432/credebl",
    "KEYCLOAK_ADMIN_PASSWORD":          e("KEYCLOAK_ADMIN_PASSWORD"),
    "KEYCLOAK_DOMAIN":                  e("KEYCLOAK_DOMAIN_INTERNAL"),
    "KEYCLOAK_ADMIN_URL":               e("KEYCLOAK_ADMIN_URL_INTERNAL"),
    "KEYCLOAK_CLIENT_SECRET":           e("KEYCLOAK_CLIENT_SECRET"),
    "KEYCLOAK_MANAGEMENT_CLIENT_SECRET": e("KEYCLOAK_CLIENT_SECRET"),
    "PLATFORM_ADMIN_KEYCLOAK_SECRET":   e("KEYCLOAK_CLIENT_SECRET"),
    "KEYCLOAK_PUBLIC_URL":              e("KEYCLOAK_PUBLIC_URL"),
    "PLATFORM_ADMIN_INITIAL_PASSWORD":  e("PLATFORM_ADMIN_INITIAL_PASSWORD"),
    "MINIO_ROOT_PASSWORD":              e("MINIO_ROOT_PASSWORD"),
    "AWS_ACCESS_KEY_ID":                e("AWS_ACCESS_KEY_ID"),
    "AWS_SECRET_ACCESS_KEY":            e("AWS_SECRET_ACCESS_KEY"),
    "AWS_S3_STOREOBJECT_ACCESS_KEY":    e("AWS_ACCESS_KEY_ID"),
    "AWS_S3_STOREOBJECT_SECRET_KEY":    e("AWS_SECRET_ACCESS_KEY"),
    "PLATFORM_SEED":                    e("PLATFORM_SEED"),
    "PLATFORM_WALLET_NAME":             e("PLATFORM_WALLET_NAME"),
    "PLATFORM_WALLET_PASSWORD":         e("PLATFORM_WALLET_PASSWORD"),
    "AGENT_API_KEY":                    e("AGENT_API_KEY"),
    # 172.17.0.1 = docker0 bridge gateway. The spawned Credo container runs on
    # Docker's default bridge network (not credebl-net), so it cannot resolve
    # the hostname 'postgres'. The public VPS IP is also unreliable because many
    # VPS providers block self-connections on the public IP (loopback via NIC).
    # 172.17.0.1 is always reachable from any default-bridge container and routes
    # through to the host's published port 5432.
    "WALLET_STORAGE_HOST":              "172.17.0.1",
    "WALLET_STORAGE_PASSWORD":          e("POSTGRES_PASSWORD"),
    "JWT_SECRET":                       e("JWT_SECRET"),
    "NEXTAUTH_SECRET":                  e("NEXTAUTH_SECRET"),
    "JWT_TOKEN_SECRET":                 e("JWT_TOKEN_SECRET"),
    "SCHEMA_FILE_SERVER_TOKEN":         e("SCHEMA_FILE_SERVER_TOKEN"),
    "CRYPTO_PRIVATE_KEY":               e("CRYPTO_PRIVATE_KEY"),
    "ADMIN_KEYCLOAK_ID":                e("ADMIN_KEYCLOAK_ID"),
    "ADMIN_KEYCLOAK_SECRET":            e("ADMIN_KEYCLOAK_SECRET"),
    "NEXTAUTH_COOKIE_DOMAIN":           "",
    "PLATFORM_ADMIN_EMAIL":             e("PLATFORM_ADMIN_EMAIL"),
    "API_ENDPOINT":                     e("API_ENDPOINT"),
    "VPS_IP":                           e("VPS_HOST"),
    "PLATFORM_WEB_URL":                 e("PLATFORM_WEB_URL"),
    "FRONT_END_URL":                    e("PLATFORM_WEB_URL"),
    "STUDIO_URL":                       e("STUDIO_URL"),
    "SOCKET_HOST":                      e("SOCKET_HOST"),
    "ENABLE_CORS_IP_LIST":              e("ENABLE_CORS_IP_LIST"),
    "APP_PROTOCOL":                     e("PROTOCOL"),
}

for key, value in replacements.items():
    pattern = re.compile(rf"^{re.escape(key)}=.*$", re.MULTILINE)
    text = pattern.sub(f"{key}={value}", text)

# Catch any remaining placeholder tokens not covered by key substitution above
text = text.replace("YOUR_VPS_IP", e("VPS_HOST"))
text = text.replace("YOUR_POSTGRES_PASSWORD", e("POSTGRES_PASSWORD"))

env_file.write_text(text, encoding="utf-8")

# Update credebl-master-table.json with VPS host values and the chosen admin email.
# platformAdminData.email/username must match PLATFORM_ADMIN_EMAIL so the seed creates
# the right user — the bootstrap then links that DB user to the Keycloak user by the same email.
config = json.loads(master_table.read_text(encoding="utf-8"))

pc = config.setdefault("platformConfigData", {})
pc["externalIp"]      = e("VPS_HOST")
pc["inboundEndpoint"] = e("VPS_HOST")
pc["apiEndpoint"]     = f"{e('PROTOCOL')}://{e('VPS_HOST')}:5000"
config["platformConfigData"] = pc

pa = config.setdefault("platformAdminData", {})
pa["email"]    = e("PLATFORM_ADMIN_EMAIL")
pa["username"] = e("PLATFORM_ADMIN_EMAIL")
config["platformAdminData"] = pa

master_table.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
PY

echo "  .env written:          $ENV_FILE"
echo "  master-table updated:  $MASTER_TABLE"

write_agent_runtime_env
echo "  agent runtime env:     $AGENT_RUNTIME_ENV_FILE"

# =============================================================================
# CREDENTIALS REPORT — print before any Docker operation
# =============================================================================

echo
echo "============================================================"
echo " CREDENTIALS REPORT — save this before continuing"
echo "============================================================"
printf " %-28s %s\n" "VPS host:"               "$VPS_HOST"
printf " %-28s %s\n" "Keycloak host:"           "$KEYCLOAK_HOST"
printf " %-28s %s\n" "Keycloak public URL:"     "$KEYCLOAK_PUBLIC_URL"
printf " %-28s %s\n" "Studio URL:"              "$STUDIO_URL"
printf " %-28s %s\n" "API URL:"                 "$PLATFORM_WEB_URL"
echo " ----------------------------------------------------------"
printf " %-28s %s\n" "Studio email:"            "$PLATFORM_ADMIN_EMAIL"
printf " %-28s %s\n" "Studio password:"         "$PLATFORM_ADMIN_INITIAL_PASSWORD"
echo " ----------------------------------------------------------"
printf " %-28s %s\n" "Postgres password:"       "$POSTGRES_PASSWORD"
printf " %-28s %s\n" "Keycloak admin password:" "$KEYCLOAK_ADMIN_PASSWORD"
printf " %-28s %s\n" "Keycloak client secret:"  "$KEYCLOAK_CLIENT_SECRET"
printf " %-28s %s\n" "MinIO root password:"     "$MINIO_ROOT_PASSWORD"
printf " %-28s %s\n" "MinIO access key ID:"     "$AWS_ACCESS_KEY_ID"
printf " %-28s %s\n" "MinIO secret key:"        "$AWS_SECRET_ACCESS_KEY"
printf " %-28s %s\n" "Platform seed:"           "$PLATFORM_SEED"
printf " %-28s %s\n" "Wallet password:"         "$PLATFORM_WALLET_PASSWORD"
printf " %-28s %s\n" "Agent API key:"           "$AGENT_API_KEY"
printf " %-28s %s\n" "JWT secret:"              "$JWT_SECRET"
printf " %-28s %s\n" "NextAuth secret:"         "$NEXTAUTH_SECRET"
printf " %-28s %s\n" "JWT token secret:"        "$JWT_TOKEN_SECRET"
printf " %-28s %s\n" "Crypto private key:"      "$CRYPTO_PRIVATE_KEY"
echo "============================================================"
echo

# =============================================================================
# DOCKER DEPLOY
# =============================================================================

cd "$CREDEBL_DIR"
mkdir -p .agent-runtime/agent-config .agent-runtime/token .agent-runtime/endpoints

# `docker compose down -v` does NOT remove built images — only containers and
# volumes. So the Studio image survives a full reset and can be reused, saving
# several minutes of Next.js build time. Build args (NEXTAUTH_SECRET, API_ENDPOINT,
# etc.) are baked in at build time — if the VPS IP or secrets changed, force a
# rebuild by answering N to the question below.
# docker compose names a build-only service image as <project>-<service>.
# When run from the credebl/ directory the project name is "credebl", so the
# Studio image is always "credebl-studio". Check for that specific image name.
STUDIO_IMAGE="credebl-studio"
SKIP_STUDIO_BUILD=false
if docker image inspect "$STUDIO_IMAGE" >/dev/null 2>&1; then
  echo
  if ask_yes_no "Studio image already exists. Skip rebuild? (answer N if VPS IP or secrets changed)" "Y"; then
    SKIP_STUDIO_BUILD=true
    echo "  Will reuse existing Studio image."
  else
    echo "  Will rebuild Studio image."
  fi
fi

if ask_yes_no "Clean reset first? (docker compose down -v --remove-orphans)" "Y"; then
  docker compose down -v --remove-orphans
fi

# Remove any stale Credo controller containers left over from previous deployments.
# These are spawned by agent-provisioning via `docker run` (outside compose scope),
# so `docker compose down` never removes them. If they hold ports 8001-9099, the
# new spin-up will fail with "port is already allocated".
echo
echo "Cleaning up stale Credo controller containers from previous deployments..."
purge_stale_credo_containers

echo
echo "Pulling images..."
docker compose pull

echo
echo "Starting the stack..."
if [ "$SKIP_STUDIO_BUILD" = "true" ]; then
  # Image already exists — skip the Next.js build entirely.
  docker compose up -d --no-build
else
  # Build Studio first (docker compose pull skips build-only services, so the
  # image doesn't exist yet). Then bring up all services without rebuilding.
  echo "Building Studio image (this may take several minutes)..."
  docker compose build studio
  docker compose up -d --no-build
fi

ensure_minio_setup

ensure_platform_admin_shared_agent

# =============================================================================
# SSL / HTTPS SETUP (only when requested)
# =============================================================================

if [ "$ENABLE_SSL" = "true" ]; then
  echo
  _ssl_label="$SSL_KEYCLOAK_DOMAIN"
  [ -n "$SSL_VPS_DOMAIN" ] && _ssl_label="$_ssl_label + $SSL_VPS_DOMAIN"
  echo "Setting up HTTPS certificates for: $_ssl_label ..."
  echo "Note: requires sudo to install nginx and run certbot."

  _ssl_args=(
    --domain      "$SSL_KEYCLOAK_DOMAIN"
    --email       "$PLATFORM_ADMIN_EMAIL"
    --credebl-dir "$CREDEBL_DIR"
  )
  [ -n "$SSL_VPS_DOMAIN" ] && _ssl_args+=(--vps-domain "$SSL_VPS_DOMAIN")

  if [ "${EUID:-$(id -u)}" -ne 0 ]; then
    sudo bash "$SCRIPT_DIR/setup-keycloak-https.sh" "${_ssl_args[@]}"
  else
    bash "$SCRIPT_DIR/setup-keycloak-https.sh" "${_ssl_args[@]}"
  fi
fi

# =============================================================================
# HEALTH CHECK + FINAL SUMMARY
# =============================================================================

echo
bash "$SCRIPT_DIR/health-check.sh"

echo
echo "============================================================"
echo " Deployment complete"
echo "============================================================"
printf " %-20s %s\n" "Studio:" "$STUDIO_URL"
printf " %-20s %s\n" "Email:"  "$PLATFORM_ADMIN_EMAIL"
printf " %-20s %s\n" "Password:" "$PLATFORM_ADMIN_INITIAL_PASSWORD"
echo "============================================================"
